// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: community.proto

package community

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommunityService_Community_GetAllCommunities_FullMethodName   = "/community.CommunityService/Community_GetAllCommunities"
	CommunityService_Community_CreateCommunity_FullMethodName     = "/community.CommunityService/Community_CreateCommunity"
	CommunityService_Community_GetUserCommunities_FullMethodName  = "/community.CommunityService/Community_GetUserCommunities"
	CommunityService_Admin_GetAllCommunityRequests_FullMethodName = "/community.CommunityService/Admin_GetAllCommunityRequests"
)

// CommunityServiceClient is the client API for CommunityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunityServiceClient interface {
	// Protected Routes
	Community_GetAllCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_CreateCommunity(ctx context.Context, in *CreateCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_GetUserCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	// Admin Routes
	Admin_GetAllCommunityRequests(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
}

type communityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunityServiceClient(cc grpc.ClientConnInterface) CommunityServiceClient {
	return &communityServiceClient{cc}
}

func (c *communityServiceClient) Community_GetAllCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetAllCommunities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_CreateCommunity(ctx context.Context, in *CreateCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_CreateCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_GetUserCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetUserCommunities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Admin_GetAllCommunityRequests(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Admin_GetAllCommunityRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunityServiceServer is the server API for CommunityService service.
// All implementations must embed UnimplementedCommunityServiceServer
// for forward compatibility.
type CommunityServiceServer interface {
	// Protected Routes
	Community_GetAllCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Community_CreateCommunity(context.Context, *CreateCommunityRequest) (*ApiResponseCommunity, error)
	Community_GetUserCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	// Admin Routes
	Admin_GetAllCommunityRequests(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	mustEmbedUnimplementedCommunityServiceServer()
}

// UnimplementedCommunityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunityServiceServer struct{}

func (UnimplementedCommunityServiceServer) Community_GetAllCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetAllCommunities not implemented")
}
func (UnimplementedCommunityServiceServer) Community_CreateCommunity(context.Context, *CreateCommunityRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_CreateCommunity not implemented")
}
func (UnimplementedCommunityServiceServer) Community_GetUserCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetUserCommunities not implemented")
}
func (UnimplementedCommunityServiceServer) Admin_GetAllCommunityRequests(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admin_GetAllCommunityRequests not implemented")
}
func (UnimplementedCommunityServiceServer) mustEmbedUnimplementedCommunityServiceServer() {}
func (UnimplementedCommunityServiceServer) testEmbeddedByValue()                          {}

// UnsafeCommunityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunityServiceServer will
// result in compilation errors.
type UnsafeCommunityServiceServer interface {
	mustEmbedUnimplementedCommunityServiceServer()
}

func RegisterCommunityServiceServer(s grpc.ServiceRegistrar, srv CommunityServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommunityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommunityService_ServiceDesc, srv)
}

func _CommunityService_Community_GetAllCommunities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetAllCommunities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetAllCommunities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetAllCommunities(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_CreateCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_CreateCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_CreateCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_CreateCommunity(ctx, req.(*CreateCommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_GetUserCommunities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetUserCommunities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetUserCommunities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetUserCommunities(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Admin_GetAllCommunityRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Admin_GetAllCommunityRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Admin_GetAllCommunityRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Admin_GetAllCommunityRequests(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

// CommunityService_ServiceDesc is the grpc.ServiceDesc for CommunityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommunityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.CommunityService",
	HandlerType: (*CommunityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Community_GetAllCommunities",
			Handler:    _CommunityService_Community_GetAllCommunities_Handler,
		},
		{
			MethodName: "Community_CreateCommunity",
			Handler:    _CommunityService_Community_CreateCommunity_Handler,
		},
		{
			MethodName: "Community_GetUserCommunities",
			Handler:    _CommunityService_Community_GetUserCommunities_Handler,
		},
		{
			MethodName: "Admin_GetAllCommunityRequests",
			Handler:    _CommunityService_Admin_GetAllCommunityRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "community.proto",
}
