version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - user_service

  user_service:
    build: ./services/user
    ports:
      - "5001:5001"
    depends_on:
      - postgres_auth
      - redis

  flask_ai:
    build: ./flask-ai
    ports:
      - "5000:5000"

  postgres_auth:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"

  postgres_post:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: post_db
    ports:
      - "5433:5432"

  postgres_user:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
