// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponseNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseNotification) Reset() {
	*x = ApiResponseNotification{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseNotification) ProtoMessage() {}

func (x *ApiResponseNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseNotification.ProtoReflect.Descriptor instead.
func (*ApiResponseNotification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponseNotification) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApiResponseNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseNotification) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	From           string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Read           bool                   `protobuf:"varint,5,opt,name=read,proto3" json:"read,omitempty"`
	Timestamp      string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetAllNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNotificationsRequest) Reset() {
	*x = GetAllNotificationsRequest{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNotificationsRequest) ProtoMessage() {}

func (x *GetAllNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNotificationResponse) Reset() {
	*x = GetAllNotificationResponse{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNotificationResponse) ProtoMessage() {}

func (x *GetAllNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetAllNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllNotificationResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type MarkNotificationAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkNotificationAsReadRequest) Reset() {
	*x = MarkNotificationAsReadRequest{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationAsReadRequest) ProtoMessage() {}

func (x *MarkNotificationAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *MarkNotificationAsReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkNotificationAsReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type DeleteNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type ClearNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearNotificationsRequest) Reset() {
	*x = ClearNotificationsRequest{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearNotificationsRequest) ProtoMessage() {}

func (x *ClearNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ClearNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ClearNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NotificationSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NotifLike       bool                   `protobuf:"varint,1,opt,name=notif_like,json=notifLike,proto3" json:"notif_like,omitempty"`
	NotifRepost     bool                   `protobuf:"varint,2,opt,name=notif_repost,json=notifRepost,proto3" json:"notif_repost,omitempty"`
	NotifFollow     bool                   `protobuf:"varint,3,opt,name=notif_follow,json=notifFollow,proto3" json:"notif_follow,omitempty"`
	NotifMention    bool                   `protobuf:"varint,4,opt,name=notif_mention,json=notifMention,proto3" json:"notif_mention,omitempty"`
	NotifCommunity  bool                   `protobuf:"varint,5,opt,name=notif_community,json=notifCommunity,proto3" json:"notif_community,omitempty"`
	NotifNewsletter bool                   `protobuf:"varint,6,opt,name=notif_newsletter,json=notifNewsletter,proto3" json:"notif_newsletter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotificationSettings) Reset() {
	*x = NotificationSettings{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSettings) ProtoMessage() {}

func (x *NotificationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSettings.ProtoReflect.Descriptor instead.
func (*NotificationSettings) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *NotificationSettings) GetNotifLike() bool {
	if x != nil {
		return x.NotifLike
	}
	return false
}

func (x *NotificationSettings) GetNotifRepost() bool {
	if x != nil {
		return x.NotifRepost
	}
	return false
}

func (x *NotificationSettings) GetNotifFollow() bool {
	if x != nil {
		return x.NotifFollow
	}
	return false
}

func (x *NotificationSettings) GetNotifMention() bool {
	if x != nil {
		return x.NotifMention
	}
	return false
}

func (x *NotificationSettings) GetNotifCommunity() bool {
	if x != nil {
		return x.NotifCommunity
	}
	return false
}

func (x *NotificationSettings) GetNotifNewsletter() bool {
	if x != nil {
		return x.NotifNewsletter
	}
	return false
}

type GetNotificationSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationSettingsRequest) Reset() {
	*x = GetNotificationSettingsRequest{}
	mi := &file_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationSettingsRequest) ProtoMessage() {}

func (x *GetNotificationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{8}
}

func (x *GetNotificationSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateNotificationSettingsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotifLike       bool                   `protobuf:"varint,2,opt,name=notif_like,json=notifLike,proto3" json:"notif_like,omitempty"`
	NotifRepost     bool                   `protobuf:"varint,3,opt,name=notif_repost,json=notifRepost,proto3" json:"notif_repost,omitempty"`
	NotifFollow     bool                   `protobuf:"varint,4,opt,name=notif_follow,json=notifFollow,proto3" json:"notif_follow,omitempty"`
	NotifMention    bool                   `protobuf:"varint,5,opt,name=notif_mention,json=notifMention,proto3" json:"notif_mention,omitempty"`
	NotifCommunity  bool                   `protobuf:"varint,6,opt,name=notif_community,json=notifCommunity,proto3" json:"notif_community,omitempty"`
	NotifNewsletter bool                   `protobuf:"varint,7,opt,name=notif_newsletter,json=notifNewsletter,proto3" json:"notif_newsletter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNotificationSettingsRequest) Reset() {
	*x = UpdateNotificationSettingsRequest{}
	mi := &file_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationSettingsRequest) ProtoMessage() {}

func (x *UpdateNotificationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNotificationSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateNotificationSettingsRequest) GetNotifLike() bool {
	if x != nil {
		return x.NotifLike
	}
	return false
}

func (x *UpdateNotificationSettingsRequest) GetNotifRepost() bool {
	if x != nil {
		return x.NotifRepost
	}
	return false
}

func (x *UpdateNotificationSettingsRequest) GetNotifFollow() bool {
	if x != nil {
		return x.NotifFollow
	}
	return false
}

func (x *UpdateNotificationSettingsRequest) GetNotifMention() bool {
	if x != nil {
		return x.NotifMention
	}
	return false
}

func (x *UpdateNotificationSettingsRequest) GetNotifCommunity() bool {
	if x != nil {
		return x.NotifCommunity
	}
	return false
}

func (x *UpdateNotificationSettingsRequest) GetNotifNewsletter() bool {
	if x != nil {
		return x.NotifNewsletter
	}
	return false
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x04user\x1a\x19google/protobuf/any.proto\"w\n" +
	"\x17ApiResponseNotification\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"\xad\x01\n" +
	"\fNotification\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x12\n" +
	"\x04read\x18\x05 \x01(\bR\x04read\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"5\n" +
	"\x1aGetAllNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"V\n" +
	"\x1aGetAllNotificationResponse\x128\n" +
	"\rnotifications\x18\x01 \x03(\v2\x12.user.NotificationR\rnotifications\"a\n" +
	"\x1dMarkNotificationAsReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\"]\n" +
	"\x19DeleteNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\"4\n" +
	"\x19ClearNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf4\x01\n" +
	"\x14NotificationSettings\x12\x1d\n" +
	"\n" +
	"notif_like\x18\x01 \x01(\bR\tnotifLike\x12!\n" +
	"\fnotif_repost\x18\x02 \x01(\bR\vnotifRepost\x12!\n" +
	"\fnotif_follow\x18\x03 \x01(\bR\vnotifFollow\x12#\n" +
	"\rnotif_mention\x18\x04 \x01(\bR\fnotifMention\x12'\n" +
	"\x0fnotif_community\x18\x05 \x01(\bR\x0enotifCommunity\x12)\n" +
	"\x10notif_newsletter\x18\x06 \x01(\bR\x0fnotifNewsletter\"9\n" +
	"\x1eGetNotificationSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9a\x02\n" +
	"!UpdateNotificationSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"notif_like\x18\x02 \x01(\bR\tnotifLike\x12!\n" +
	"\fnotif_repost\x18\x03 \x01(\bR\vnotifRepost\x12!\n" +
	"\fnotif_follow\x18\x04 \x01(\bR\vnotifFollow\x12#\n" +
	"\rnotif_mention\x18\x05 \x01(\bR\fnotifMention\x12'\n" +
	"\x0fnotif_community\x18\x06 \x01(\bR\x0enotifCommunity\x12)\n" +
	"\x10notif_newsletter\x18\a \x01(\bR\x0fnotifNewsletter2\xf3\x04\n" +
	"\x13NotificationService\x12c\n" +
	" Notification_GetAllNotifications\x12 .user.GetAllNotificationsRequest\x1a\x1d.user.ApiResponseNotification\x12i\n" +
	"#Notification_MarkNotificationAsRead\x12#.user.MarkNotificationAsReadRequest\x1a\x1d.user.ApiResponseNotification\x12a\n" +
	"\x1fNotification_DeleteNotification\x12\x1f.user.DeleteNotificationRequest\x1a\x1d.user.ApiResponseNotification\x12a\n" +
	"\x1fNotification_ClearNotifications\x12\x1f.user.ClearNotificationsRequest\x1a\x1d.user.ApiResponseNotification\x12_\n" +
	"\x18Notification_GetSettings\x12$.user.GetNotificationSettingsRequest\x1a\x1d.user.ApiResponseNotification\x12e\n" +
	"\x1bNotification_UpdateSettings\x12'.user.UpdateNotificationSettingsRequest\x1a\x1d.user.ApiResponseNotificationB\x0fZ\rnotification/b\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_notification_proto_goTypes = []any{
	(*ApiResponseNotification)(nil),           // 0: user.ApiResponseNotification
	(*Notification)(nil),                      // 1: user.Notification
	(*GetAllNotificationsRequest)(nil),        // 2: user.GetAllNotificationsRequest
	(*GetAllNotificationResponse)(nil),        // 3: user.GetAllNotificationResponse
	(*MarkNotificationAsReadRequest)(nil),     // 4: user.MarkNotificationAsReadRequest
	(*DeleteNotificationRequest)(nil),         // 5: user.DeleteNotificationRequest
	(*ClearNotificationsRequest)(nil),         // 6: user.ClearNotificationsRequest
	(*NotificationSettings)(nil),              // 7: user.NotificationSettings
	(*GetNotificationSettingsRequest)(nil),    // 8: user.GetNotificationSettingsRequest
	(*UpdateNotificationSettingsRequest)(nil), // 9: user.UpdateNotificationSettingsRequest
	(*anypb.Any)(nil),                         // 10: google.protobuf.Any
}
var file_notification_proto_depIdxs = []int32{
	10, // 0: user.ApiResponseNotification.data:type_name -> google.protobuf.Any
	1,  // 1: user.GetAllNotificationResponse.notifications:type_name -> user.Notification
	2,  // 2: user.NotificationService.Notification_GetAllNotifications:input_type -> user.GetAllNotificationsRequest
	4,  // 3: user.NotificationService.Notification_MarkNotificationAsRead:input_type -> user.MarkNotificationAsReadRequest
	5,  // 4: user.NotificationService.Notification_DeleteNotification:input_type -> user.DeleteNotificationRequest
	6,  // 5: user.NotificationService.Notification_ClearNotifications:input_type -> user.ClearNotificationsRequest
	8,  // 6: user.NotificationService.Notification_GetSettings:input_type -> user.GetNotificationSettingsRequest
	9,  // 7: user.NotificationService.Notification_UpdateSettings:input_type -> user.UpdateNotificationSettingsRequest
	0,  // 8: user.NotificationService.Notification_GetAllNotifications:output_type -> user.ApiResponseNotification
	0,  // 9: user.NotificationService.Notification_MarkNotificationAsRead:output_type -> user.ApiResponseNotification
	0,  // 10: user.NotificationService.Notification_DeleteNotification:output_type -> user.ApiResponseNotification
	0,  // 11: user.NotificationService.Notification_ClearNotifications:output_type -> user.ApiResponseNotification
	0,  // 12: user.NotificationService.Notification_GetSettings:output_type -> user.ApiResponseNotification
	0,  // 13: user.NotificationService.Notification_UpdateSettings:output_type -> user.ApiResponseNotification
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
