syntax = "proto3";

package community;

import "google/protobuf/any.proto";

option go_package = "community/";

service CommunityService {
    // Protected Routes
    rpc Community_GetAllCommunities (StringCommunity) returns (ApiResponseCommunity);
    rpc Community_CreateCommunity (CreateCommunityRequest) returns (ApiResponseCommunity);
    rpc Community_GetUserCommunities (StringCommunity) returns (ApiResponseCommunity);
    rpc Community_GetUserPendingCommunities (StringCommunity) returns (ApiResponseCommunity);
    rpc Community_GetUserPendingApprovalCommunities (StringCommunity) returns (ApiResponseCommunity);
    rpc Community_GetCategories (StringCommunity) returns (GetCategoriesResponse);
    rpc Community_GetCommunityById (StringCommunity) returns (ApiResponseCommunity);

    // Admin Routes
    rpc Admin_GetAllCommunityRequests (StringCommunity) returns (ApiResponseCommunity);
    rpc Admin_ApproveCommunity (StringCommunity) returns (ApiResponseCommunity);
    rpc Admin_RejectCommunity (RejectCommunityRequest) returns (ApiResponseCommunity);
}

message ApiResponseCommunity {
    bool success = 1;
    string message = 2;
    google.protobuf.Any data = 3;
}

message StringCommunity {
    string value = 1;
}

message BoolCommunity {
    bool value = 1;
}

message RejectCommunityRequest {
    string community_id = 1;
    string reason = 2;
}

message GetCommunitiesResponse {
    repeated Community communities = 1;
}

message GetCategoriesResponse {
    repeated string categories = 1;
}

message Community {
    string community_id = 1;
    string community_name = 2;
    string description = 3;
    repeated string categories = 4;
    string created_at = 5;
    string rules = 6;
    string creator_id = 7;
    string banner_image = 8;
    string icon_image = 9;
    int32 member_count = 10;
}

message CreateCommunityRequest {
    string community_name = 1;
    string description = 2;
    repeated string categories = 3;
    string user_id = 4;
    string rules = 5;
    string community_id = 6;
    string banner_image = 7;
    string icon_image = 8;
}

message CommunityCategories {
    repeated string categories = 1;
}