syntax = "proto3";

package media;

option go_package = "media/";

service MediaService {
  rpc UploadMedia(UploadMediaRequest) returns (UploadMediaResponse);
  rpc DeleteMedia(DeleteMediaRequest) returns (DeleteMediaResponse);
}

message UploadMediaRequest {
  bytes file = 1;
  string file_name = 2;
  string content_type = 3;
  string usage_type = 4;
  string owner_id = 5;
}

message UploadMediaResponse {
  bool success = 1;
  string url = 2;
}

message DeleteMediaRequest {
  string file_url = 1;
}

message DeleteMediaResponse {
  bool success = 1;
}
