syntax = "proto3";

package redis;

option go_package = "redis/";

service RedisService {
  rpc SetKey(SetKeyRequest) returns (SetKeyResponse);
  rpc GetKey(GetKeyRequest) returns (GetKeyResponse);
  rpc DeleteKey(DeleteKeyRequest) returns (DeleteKeyResponse);
}

message SetKeyRequest {
  string key = 1;
  string value = 2;
  int32 expiration_seconds = 3;
}

message SetKeyResponse {
  bool success = 1;
}

message GetKeyRequest {
  string key = 1;
}

message GetKeyResponse {
  string value = 1;
  bool found = 2;
}

message DeleteKeyRequest {
  string key = 1;
}

message DeleteKeyResponse {
  bool success = 1;
}
