syntax = "proto3";

package user;

import "google/protobuf/any.proto";

option go_package = "user/";

service UserService {
    rpc User_Register (RegisterRequest) returns (ApiResponse);
    rpc User_Login (LoginRequest) returns (ApiResponse);
    rpc User_RequestVerificationCode (VerificationRequest) returns (ApiResponse);
    rpc User_ValidateVerificationCode (ValidateCodeRequest) returns (ApiResponse);
    rpc User_GetSecurityQuestion (GetSecurityQuestionRequest) returns (ApiResponse);
    rpc User_ValidateSecurityAnswer (ValidateSecurityAnswerRequest) returns (ApiResponse);
    rpc User_ResetPassword (ResetPasswordRequest) returns (ApiResponse);

    // protected routes
    rpc User_GetProfile (GetProfileRequest) returns (ApiResponse);
    rpc User_ChangePassword (ChangePasswordRequest) returns (ApiResponse);

    rpc User_FollowUser (FollowUserRequest) returns (ApiResponse);
    rpc User_BlockUser (BlockUserRequest) returns (ApiResponse);
    rpc User_UnFollowUser (UnFollowUserRequest) returns (ApiResponse);
    rpc User_UnBlockUser (UnBlockUserRequest) returns (ApiResponse);

    rpc User_GetSettings (GetSettingsRequest) returns (ApiResponse);
    rpc User_UpdateSettings (UpdateSettingsRequest) returns (ApiResponse);
    rpc User_DeactivateAccount (DeactivateAccountRequest) returns (ApiResponse);

    rpc User_GetAllFollowers (GetAllFollowersRequest) returns (ApiResponse);
    rpc User_GetAllFollowing (GetAllFollowingRequest) returns (ApiResponse);

    rpc User_SubmitVerifyAccountRequest (SubmitVerifyAccountRequest) returns (ApiResponse);
    rpc User_GetAllVerifyAccountRequest (GetAllVerifyAccountRequest) returns (ApiResponse);
}

message ApiResponse {
    bool success = 1;
    string message = 2;
    google.protobuf.Any data = 3;
}

message String {
    string value = 1;
}

message Bool {
    bool value = 1;
}

message UserProfile {
    string user_id = 1;
    string username = 2;
    string name = 3;
    string bio = 4;
    bool is_verified = 5;
    int32 followers = 6;
    int32 following = 7;
}

message GetProfileRequest {
    string user_id = 1;
    string requester_id = 2;
}

message RegisterRequest {
    string email = 1;
    string password = 2;
    string google_auth_id = 3;
    string username = 4;
    string name = 5;
    string security_question = 6;
    string security_answer = 7;
    string date_of_birth = 8;
    bytes profile_picture = 9;
    bytes banner = 10;
    bool wants_newsletter = 11;
    string gender = 12;
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message VerificationRequest {
    string email = 1;
}

message ValidateCodeRequest {
    string email = 1;
    string code = 2;
}

message ChangePasswordRequest {
    string email = 1;
    string old_password = 2;
    string new_password = 3;
    string user_id = 4;
}

message GetSecurityQuestionRequest {
    string email = 1;
}

message ResetPasswordRequest {
    string email = 1;
    string code = 2;
    string new_password = 3;
}

message ValidateSecurityAnswerRequest {
    string email = 1;
    string answer = 2;
    string question = 3;
}

message FollowUserRequest {
    string user_id = 1;
    string to_follow_id = 2;
}

message BlockUserRequest {
    string user_id = 1;
    string to_block_id = 2;
}

message UnFollowUserRequest {
    string user_id = 1;
    string to_unfollow_id = 2;
}

message UnBlockUserRequest {
    string user_id = 1;
    string to_unblock_id = 2;
}

message GetSettingsRequest {
    string user_id = 1;
}

message UpdateSettingsRequest {
    string user_id = 1;
    string font_size = 2;
    string font_color = 3;
    bool private = 4;
    bool notif_like = 5;
    bool notif_repost = 6;
    bool notif_follow = 7;
    bool notif_mentions = 8;
    bool notif_community = 9;
}

message UserSettings {
    string font_size = 1;
    string font_color = 2;
    bool private = 3;
    bool notif_like = 4;
    bool notif_repost = 5;
    bool notif_follow = 6;
    bool notif_mentions = 7;
    bool notif_community = 8;
}

message DeactivateAccountRequest {
    string user_id = 1;
    string password = 2;
}

message SubmitVerifyAccountRequest {
    string user_id = 1;
    string identity_card_number = 2;
    string selfie_url = 3;
    string reason_text = 4;
}

message VerifyAccountRequest {
    string user_id = 1;
    string id = 2;
    string reason_text = 3;
    string status = 4;
    string submitted_at = 5;
}

message GetAllVerifyAccountRequest {
    string user_id = 1;
    string password = 2;
}

message GetAllVerifyAccountResponse {
    repeated VerifyAccountRequest requests = 1;
}

message GetAllFollowersRequest {
    string user_id = 1;
    string requester_id = 2;
}

message GetAllFollowingRequest {
    string user_id = 1;
    string requester_id = 2;
}

message AllFollowersResponse {
    repeated String followers = 1;
}

message AllFollowingResponse {
    repeated String following = 1;
}