// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_User_Register_FullMethodName                 = "/user.UserService/User_Register"
	UserService_User_Login_FullMethodName                    = "/user.UserService/User_Login"
	UserService_User_RequestVerificationCode_FullMethodName  = "/user.UserService/User_RequestVerificationCode"
	UserService_User_ValidateVerificationCode_FullMethodName = "/user.UserService/User_ValidateVerificationCode"
	UserService_User_GetSecurityQuestion_FullMethodName      = "/user.UserService/User_GetSecurityQuestion"
	UserService_User_ValidateSecurityAnswer_FullMethodName   = "/user.UserService/User_ValidateSecurityAnswer"
	UserService_User_ResetPassword_FullMethodName            = "/user.UserService/User_ResetPassword"
	UserService_User_GetProfile_FullMethodName               = "/user.UserService/User_GetProfile"
	UserService_User_ChangePassword_FullMethodName           = "/user.UserService/User_ChangePassword"
	UserService_User_FollowUser_FullMethodName               = "/user.UserService/User_FollowUser"
	UserService_User_BlockUser_FullMethodName                = "/user.UserService/User_BlockUser"
	UserService_User_UnFollowUser_FullMethodName             = "/user.UserService/User_UnFollowUser"
	UserService_User_UnBlockUser_FullMethodName              = "/user.UserService/User_UnBlockUser"
	UserService_User_GetSettings_FullMethodName              = "/user.UserService/User_GetSettings"
	UserService_User_UpdateSettings_FullMethodName           = "/user.UserService/User_UpdateSettings"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	User_Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_RequestVerificationCode(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_ValidateVerificationCode(ctx context.Context, in *ValidateCodeRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_GetSecurityQuestion(ctx context.Context, in *GetSecurityQuestionRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_ValidateSecurityAnswer(ctx context.Context, in *ValidateSecurityAnswerRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	// protected routes
	User_GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_UnFollowUser(ctx context.Context, in *UnFollowUserRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_UnBlockUser(ctx context.Context, in *UnBlockUserRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	User_UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*ApiResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) User_Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_RequestVerificationCode(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_RequestVerificationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_ValidateVerificationCode(ctx context.Context, in *ValidateCodeRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_ValidateVerificationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetSecurityQuestion(ctx context.Context, in *GetSecurityQuestionRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_GetSecurityQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_ValidateSecurityAnswer(ctx context.Context, in *ValidateSecurityAnswerRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_ValidateSecurityAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_UnFollowUser(ctx context.Context, in *UnFollowUserRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_UnFollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_UnBlockUser(ctx context.Context, in *UnBlockUserRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_UnBlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_User_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	User_Register(context.Context, *RegisterRequest) (*ApiResponse, error)
	User_Login(context.Context, *LoginRequest) (*ApiResponse, error)
	User_RequestVerificationCode(context.Context, *VerificationRequest) (*ApiResponse, error)
	User_ValidateVerificationCode(context.Context, *ValidateCodeRequest) (*ApiResponse, error)
	User_GetSecurityQuestion(context.Context, *GetSecurityQuestionRequest) (*ApiResponse, error)
	User_ValidateSecurityAnswer(context.Context, *ValidateSecurityAnswerRequest) (*ApiResponse, error)
	User_ResetPassword(context.Context, *ResetPasswordRequest) (*ApiResponse, error)
	// protected routes
	User_GetProfile(context.Context, *GetProfileRequest) (*ApiResponse, error)
	User_ChangePassword(context.Context, *ChangePasswordRequest) (*ApiResponse, error)
	User_FollowUser(context.Context, *FollowUserRequest) (*ApiResponse, error)
	User_BlockUser(context.Context, *BlockUserRequest) (*ApiResponse, error)
	User_UnFollowUser(context.Context, *UnFollowUserRequest) (*ApiResponse, error)
	User_UnBlockUser(context.Context, *UnBlockUserRequest) (*ApiResponse, error)
	User_GetSettings(context.Context, *GetSettingsRequest) (*ApiResponse, error)
	User_UpdateSettings(context.Context, *UpdateSettingsRequest) (*ApiResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) User_Register(context.Context, *RegisterRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_Register not implemented")
}
func (UnimplementedUserServiceServer) User_Login(context.Context, *LoginRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_Login not implemented")
}
func (UnimplementedUserServiceServer) User_RequestVerificationCode(context.Context, *VerificationRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_RequestVerificationCode not implemented")
}
func (UnimplementedUserServiceServer) User_ValidateVerificationCode(context.Context, *ValidateCodeRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_ValidateVerificationCode not implemented")
}
func (UnimplementedUserServiceServer) User_GetSecurityQuestion(context.Context, *GetSecurityQuestionRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetSecurityQuestion not implemented")
}
func (UnimplementedUserServiceServer) User_ValidateSecurityAnswer(context.Context, *ValidateSecurityAnswerRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_ValidateSecurityAnswer not implemented")
}
func (UnimplementedUserServiceServer) User_ResetPassword(context.Context, *ResetPasswordRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_ResetPassword not implemented")
}
func (UnimplementedUserServiceServer) User_GetProfile(context.Context, *GetProfileRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetProfile not implemented")
}
func (UnimplementedUserServiceServer) User_ChangePassword(context.Context, *ChangePasswordRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_ChangePassword not implemented")
}
func (UnimplementedUserServiceServer) User_FollowUser(context.Context, *FollowUserRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_FollowUser not implemented")
}
func (UnimplementedUserServiceServer) User_BlockUser(context.Context, *BlockUserRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_BlockUser not implemented")
}
func (UnimplementedUserServiceServer) User_UnFollowUser(context.Context, *UnFollowUserRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_UnFollowUser not implemented")
}
func (UnimplementedUserServiceServer) User_UnBlockUser(context.Context, *UnBlockUserRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_UnBlockUser not implemented")
}
func (UnimplementedUserServiceServer) User_GetSettings(context.Context, *GetSettingsRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetSettings not implemented")
}
func (UnimplementedUserServiceServer) User_UpdateSettings(context.Context, *UpdateSettingsRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_UpdateSettings not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_RequestVerificationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_RequestVerificationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_RequestVerificationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_RequestVerificationCode(ctx, req.(*VerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_ValidateVerificationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_ValidateVerificationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_ValidateVerificationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_ValidateVerificationCode(ctx, req.(*ValidateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetSecurityQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecurityQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetSecurityQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetSecurityQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetSecurityQuestion(ctx, req.(*GetSecurityQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_ValidateSecurityAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSecurityAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_ValidateSecurityAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_ValidateSecurityAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_ValidateSecurityAnswer(ctx, req.(*ValidateSecurityAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_BlockUser(ctx, req.(*BlockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_UnFollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnFollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_UnFollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_UnFollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_UnFollowUser(ctx, req.(*UnFollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_UnBlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnBlockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_UnBlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_UnBlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_UnBlockUser(ctx, req.(*UnBlockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "User_Register",
			Handler:    _UserService_User_Register_Handler,
		},
		{
			MethodName: "User_Login",
			Handler:    _UserService_User_Login_Handler,
		},
		{
			MethodName: "User_RequestVerificationCode",
			Handler:    _UserService_User_RequestVerificationCode_Handler,
		},
		{
			MethodName: "User_ValidateVerificationCode",
			Handler:    _UserService_User_ValidateVerificationCode_Handler,
		},
		{
			MethodName: "User_GetSecurityQuestion",
			Handler:    _UserService_User_GetSecurityQuestion_Handler,
		},
		{
			MethodName: "User_ValidateSecurityAnswer",
			Handler:    _UserService_User_ValidateSecurityAnswer_Handler,
		},
		{
			MethodName: "User_ResetPassword",
			Handler:    _UserService_User_ResetPassword_Handler,
		},
		{
			MethodName: "User_GetProfile",
			Handler:    _UserService_User_GetProfile_Handler,
		},
		{
			MethodName: "User_ChangePassword",
			Handler:    _UserService_User_ChangePassword_Handler,
		},
		{
			MethodName: "User_FollowUser",
			Handler:    _UserService_User_FollowUser_Handler,
		},
		{
			MethodName: "User_BlockUser",
			Handler:    _UserService_User_BlockUser_Handler,
		},
		{
			MethodName: "User_UnFollowUser",
			Handler:    _UserService_User_UnFollowUser_Handler,
		},
		{
			MethodName: "User_UnBlockUser",
			Handler:    _UserService_User_UnBlockUser_Handler,
		},
		{
			MethodName: "User_GetSettings",
			Handler:    _UserService_User_GetSettings_Handler,
		},
		{
			MethodName: "User_UpdateSettings",
			Handler:    _UserService_User_UpdateSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
