// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_User_Register_FullMethodName                   = "/user.UserService/User_Register"
	UserService_User_Login_FullMethodName                      = "/user.UserService/User_Login"
	UserService_User_RequestVerificationCode_FullMethodName    = "/user.UserService/User_RequestVerificationCode"
	UserService_User_ValidateVerificationCode_FullMethodName   = "/user.UserService/User_ValidateVerificationCode"
	UserService_User_GetSecurityQuestion_FullMethodName        = "/user.UserService/User_GetSecurityQuestion"
	UserService_User_ValidateSecurityAnswer_FullMethodName     = "/user.UserService/User_ValidateSecurityAnswer"
	UserService_User_ResetPassword_FullMethodName              = "/user.UserService/User_ResetPassword"
	UserService_User_GetProfile_FullMethodName                 = "/user.UserService/User_GetProfile"
	UserService_User_GetUserId_FullMethodName                  = "/user.UserService/User_GetUserId"
	UserService_User_ChangePassword_FullMethodName             = "/user.UserService/User_ChangePassword"
	UserService_User_UpdateProfile_FullMethodName              = "/user.UserService/User_UpdateProfile"
	UserService_User_SearchPeople_FullMethodName               = "/user.UserService/User_SearchPeople"
	UserService_User_GetSelfProfile_FullMethodName             = "/user.UserService/User_GetSelfProfile"
	UserService_User_FollowUser_FullMethodName                 = "/user.UserService/User_FollowUser"
	UserService_User_BlockUser_FullMethodName                  = "/user.UserService/User_BlockUser"
	UserService_User_UnFollowUser_FullMethodName               = "/user.UserService/User_UnFollowUser"
	UserService_User_UnBlockUser_FullMethodName                = "/user.UserService/User_UnBlockUser"
	UserService_User_GetSettings_FullMethodName                = "/user.UserService/User_GetSettings"
	UserService_User_UpdateSettings_FullMethodName             = "/user.UserService/User_UpdateSettings"
	UserService_User_DeactivateAccount_FullMethodName          = "/user.UserService/User_DeactivateAccount"
	UserService_User_GetAllFollowers_FullMethodName            = "/user.UserService/User_GetAllFollowers"
	UserService_User_GetAllFollowing_FullMethodName            = "/user.UserService/User_GetAllFollowing"
	UserService_User_GetAllBlocked_FullMethodName              = "/user.UserService/User_GetAllBlocked"
	UserService_User_SubmitVerifyAccountRequest_FullMethodName = "/user.UserService/User_SubmitVerifyAccountRequest"
	UserService_User_GetAllVerifyAccountRequest_FullMethodName = "/user.UserService/User_GetAllVerifyAccountRequest"
	UserService_User_IsUserPrivate_FullMethodName              = "/user.UserService/User_IsUserPrivate"
	UserService_User_IsUserFollowing_FullMethodName            = "/user.UserService/User_IsUserFollowing"
	UserService_User_RefreshToken_FullMethodName               = "/user.UserService/User_RefreshToken"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	User_Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_RequestVerificationCode(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_ValidateVerificationCode(ctx context.Context, in *ValidateCodeRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_GetSecurityQuestion(ctx context.Context, in *GetSecurityQuestionRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_ValidateSecurityAnswer(ctx context.Context, in *ValidateSecurityAnswerRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	// protected routes
	User_GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_GetUserId(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_UpdateProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_SearchPeople(ctx context.Context, in *SearchPeopleRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_GetSelfProfile(ctx context.Context, in *StringUser, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_UnFollowUser(ctx context.Context, in *UnFollowUserRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_UnBlockUser(ctx context.Context, in *UnBlockUserRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_DeactivateAccount(ctx context.Context, in *DeactivateAccountRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_GetAllFollowers(ctx context.Context, in *GetAllFollowersRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_GetAllFollowing(ctx context.Context, in *GetAllFollowingRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_GetAllBlocked(ctx context.Context, in *StringUser, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_SubmitVerifyAccountRequest(ctx context.Context, in *SubmitVerifyAccountRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_GetAllVerifyAccountRequest(ctx context.Context, in *GetAllVerifyAccountRequest, opts ...grpc.CallOption) (*ApiResponseUser, error)
	User_IsUserPrivate(ctx context.Context, in *IsAccountPrivateRequest, opts ...grpc.CallOption) (*BoolUser, error)
	User_IsUserFollowing(ctx context.Context, in *IsUserFollowingRequest, opts ...grpc.CallOption) (*BoolUser, error)
	User_RefreshToken(ctx context.Context, in *StringUser, opts ...grpc.CallOption) (*ApiResponseUser, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) User_Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_RequestVerificationCode(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_RequestVerificationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_ValidateVerificationCode(ctx context.Context, in *ValidateCodeRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_ValidateVerificationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetSecurityQuestion(ctx context.Context, in *GetSecurityQuestionRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetSecurityQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_ValidateSecurityAnswer(ctx context.Context, in *ValidateSecurityAnswerRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_ValidateSecurityAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetUserId(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_UpdateProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_SearchPeople(ctx context.Context, in *SearchPeopleRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_SearchPeople_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetSelfProfile(ctx context.Context, in *StringUser, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetSelfProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_UnFollowUser(ctx context.Context, in *UnFollowUserRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_UnFollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_UnBlockUser(ctx context.Context, in *UnBlockUserRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_UnBlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_DeactivateAccount(ctx context.Context, in *DeactivateAccountRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_DeactivateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetAllFollowers(ctx context.Context, in *GetAllFollowersRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetAllFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetAllFollowing(ctx context.Context, in *GetAllFollowingRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetAllFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetAllBlocked(ctx context.Context, in *StringUser, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetAllBlocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_SubmitVerifyAccountRequest(ctx context.Context, in *SubmitVerifyAccountRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_SubmitVerifyAccountRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_GetAllVerifyAccountRequest(ctx context.Context, in *GetAllVerifyAccountRequest, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_GetAllVerifyAccountRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_IsUserPrivate(ctx context.Context, in *IsAccountPrivateRequest, opts ...grpc.CallOption) (*BoolUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolUser)
	err := c.cc.Invoke(ctx, UserService_User_IsUserPrivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_IsUserFollowing(ctx context.Context, in *IsUserFollowingRequest, opts ...grpc.CallOption) (*BoolUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolUser)
	err := c.cc.Invoke(ctx, UserService_User_IsUserFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User_RefreshToken(ctx context.Context, in *StringUser, opts ...grpc.CallOption) (*ApiResponseUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUser)
	err := c.cc.Invoke(ctx, UserService_User_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	User_Register(context.Context, *RegisterRequest) (*ApiResponseUser, error)
	User_Login(context.Context, *LoginRequest) (*ApiResponseUser, error)
	User_RequestVerificationCode(context.Context, *VerificationRequest) (*ApiResponseUser, error)
	User_ValidateVerificationCode(context.Context, *ValidateCodeRequest) (*ApiResponseUser, error)
	User_GetSecurityQuestion(context.Context, *GetSecurityQuestionRequest) (*ApiResponseUser, error)
	User_ValidateSecurityAnswer(context.Context, *ValidateSecurityAnswerRequest) (*ApiResponseUser, error)
	User_ResetPassword(context.Context, *ResetPasswordRequest) (*ApiResponseUser, error)
	// protected routes
	User_GetProfile(context.Context, *GetProfileRequest) (*ApiResponseUser, error)
	User_GetUserId(context.Context, *GetProfileRequest) (*ApiResponseUser, error)
	User_ChangePassword(context.Context, *ChangePasswordRequest) (*ApiResponseUser, error)
	User_UpdateProfile(context.Context, *UpdateUserProfileRequest) (*ApiResponseUser, error)
	User_SearchPeople(context.Context, *SearchPeopleRequest) (*ApiResponseUser, error)
	User_GetSelfProfile(context.Context, *StringUser) (*ApiResponseUser, error)
	User_FollowUser(context.Context, *FollowUserRequest) (*ApiResponseUser, error)
	User_BlockUser(context.Context, *BlockUserRequest) (*ApiResponseUser, error)
	User_UnFollowUser(context.Context, *UnFollowUserRequest) (*ApiResponseUser, error)
	User_UnBlockUser(context.Context, *UnBlockUserRequest) (*ApiResponseUser, error)
	User_GetSettings(context.Context, *GetSettingsRequest) (*ApiResponseUser, error)
	User_UpdateSettings(context.Context, *UpdateSettingsRequest) (*ApiResponseUser, error)
	User_DeactivateAccount(context.Context, *DeactivateAccountRequest) (*ApiResponseUser, error)
	User_GetAllFollowers(context.Context, *GetAllFollowersRequest) (*ApiResponseUser, error)
	User_GetAllFollowing(context.Context, *GetAllFollowingRequest) (*ApiResponseUser, error)
	User_GetAllBlocked(context.Context, *StringUser) (*ApiResponseUser, error)
	User_SubmitVerifyAccountRequest(context.Context, *SubmitVerifyAccountRequest) (*ApiResponseUser, error)
	User_GetAllVerifyAccountRequest(context.Context, *GetAllVerifyAccountRequest) (*ApiResponseUser, error)
	User_IsUserPrivate(context.Context, *IsAccountPrivateRequest) (*BoolUser, error)
	User_IsUserFollowing(context.Context, *IsUserFollowingRequest) (*BoolUser, error)
	User_RefreshToken(context.Context, *StringUser) (*ApiResponseUser, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) User_Register(context.Context, *RegisterRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_Register not implemented")
}
func (UnimplementedUserServiceServer) User_Login(context.Context, *LoginRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_Login not implemented")
}
func (UnimplementedUserServiceServer) User_RequestVerificationCode(context.Context, *VerificationRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_RequestVerificationCode not implemented")
}
func (UnimplementedUserServiceServer) User_ValidateVerificationCode(context.Context, *ValidateCodeRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_ValidateVerificationCode not implemented")
}
func (UnimplementedUserServiceServer) User_GetSecurityQuestion(context.Context, *GetSecurityQuestionRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetSecurityQuestion not implemented")
}
func (UnimplementedUserServiceServer) User_ValidateSecurityAnswer(context.Context, *ValidateSecurityAnswerRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_ValidateSecurityAnswer not implemented")
}
func (UnimplementedUserServiceServer) User_ResetPassword(context.Context, *ResetPasswordRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_ResetPassword not implemented")
}
func (UnimplementedUserServiceServer) User_GetProfile(context.Context, *GetProfileRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetProfile not implemented")
}
func (UnimplementedUserServiceServer) User_GetUserId(context.Context, *GetProfileRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetUserId not implemented")
}
func (UnimplementedUserServiceServer) User_ChangePassword(context.Context, *ChangePasswordRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_ChangePassword not implemented")
}
func (UnimplementedUserServiceServer) User_UpdateProfile(context.Context, *UpdateUserProfileRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_UpdateProfile not implemented")
}
func (UnimplementedUserServiceServer) User_SearchPeople(context.Context, *SearchPeopleRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_SearchPeople not implemented")
}
func (UnimplementedUserServiceServer) User_GetSelfProfile(context.Context, *StringUser) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetSelfProfile not implemented")
}
func (UnimplementedUserServiceServer) User_FollowUser(context.Context, *FollowUserRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_FollowUser not implemented")
}
func (UnimplementedUserServiceServer) User_BlockUser(context.Context, *BlockUserRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_BlockUser not implemented")
}
func (UnimplementedUserServiceServer) User_UnFollowUser(context.Context, *UnFollowUserRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_UnFollowUser not implemented")
}
func (UnimplementedUserServiceServer) User_UnBlockUser(context.Context, *UnBlockUserRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_UnBlockUser not implemented")
}
func (UnimplementedUserServiceServer) User_GetSettings(context.Context, *GetSettingsRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetSettings not implemented")
}
func (UnimplementedUserServiceServer) User_UpdateSettings(context.Context, *UpdateSettingsRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_UpdateSettings not implemented")
}
func (UnimplementedUserServiceServer) User_DeactivateAccount(context.Context, *DeactivateAccountRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_DeactivateAccount not implemented")
}
func (UnimplementedUserServiceServer) User_GetAllFollowers(context.Context, *GetAllFollowersRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetAllFollowers not implemented")
}
func (UnimplementedUserServiceServer) User_GetAllFollowing(context.Context, *GetAllFollowingRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetAllFollowing not implemented")
}
func (UnimplementedUserServiceServer) User_GetAllBlocked(context.Context, *StringUser) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetAllBlocked not implemented")
}
func (UnimplementedUserServiceServer) User_SubmitVerifyAccountRequest(context.Context, *SubmitVerifyAccountRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_SubmitVerifyAccountRequest not implemented")
}
func (UnimplementedUserServiceServer) User_GetAllVerifyAccountRequest(context.Context, *GetAllVerifyAccountRequest) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_GetAllVerifyAccountRequest not implemented")
}
func (UnimplementedUserServiceServer) User_IsUserPrivate(context.Context, *IsAccountPrivateRequest) (*BoolUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_IsUserPrivate not implemented")
}
func (UnimplementedUserServiceServer) User_IsUserFollowing(context.Context, *IsUserFollowingRequest) (*BoolUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_IsUserFollowing not implemented")
}
func (UnimplementedUserServiceServer) User_RefreshToken(context.Context, *StringUser) (*ApiResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_RefreshToken not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_RequestVerificationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_RequestVerificationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_RequestVerificationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_RequestVerificationCode(ctx, req.(*VerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_ValidateVerificationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_ValidateVerificationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_ValidateVerificationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_ValidateVerificationCode(ctx, req.(*ValidateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetSecurityQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecurityQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetSecurityQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetSecurityQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetSecurityQuestion(ctx, req.(*GetSecurityQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_ValidateSecurityAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSecurityAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_ValidateSecurityAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_ValidateSecurityAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_ValidateSecurityAnswer(ctx, req.(*ValidateSecurityAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetUserId(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_UpdateProfile(ctx, req.(*UpdateUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_SearchPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPeopleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_SearchPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_SearchPeople_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_SearchPeople(ctx, req.(*SearchPeopleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetSelfProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetSelfProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetSelfProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetSelfProfile(ctx, req.(*StringUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_BlockUser(ctx, req.(*BlockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_UnFollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnFollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_UnFollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_UnFollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_UnFollowUser(ctx, req.(*UnFollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_UnBlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnBlockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_UnBlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_UnBlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_UnBlockUser(ctx, req.(*UnBlockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_DeactivateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_DeactivateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_DeactivateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_DeactivateAccount(ctx, req.(*DeactivateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetAllFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetAllFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetAllFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetAllFollowers(ctx, req.(*GetAllFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetAllFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetAllFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetAllFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetAllFollowing(ctx, req.(*GetAllFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetAllBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetAllBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetAllBlocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetAllBlocked(ctx, req.(*StringUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_SubmitVerifyAccountRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitVerifyAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_SubmitVerifyAccountRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_SubmitVerifyAccountRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_SubmitVerifyAccountRequest(ctx, req.(*SubmitVerifyAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_GetAllVerifyAccountRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllVerifyAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_GetAllVerifyAccountRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_GetAllVerifyAccountRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_GetAllVerifyAccountRequest(ctx, req.(*GetAllVerifyAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_IsUserPrivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAccountPrivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_IsUserPrivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_IsUserPrivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_IsUserPrivate(ctx, req.(*IsAccountPrivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_IsUserFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUserFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_IsUserFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_IsUserFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_IsUserFollowing(ctx, req.(*IsUserFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User_RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_User_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User_RefreshToken(ctx, req.(*StringUser))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "User_Register",
			Handler:    _UserService_User_Register_Handler,
		},
		{
			MethodName: "User_Login",
			Handler:    _UserService_User_Login_Handler,
		},
		{
			MethodName: "User_RequestVerificationCode",
			Handler:    _UserService_User_RequestVerificationCode_Handler,
		},
		{
			MethodName: "User_ValidateVerificationCode",
			Handler:    _UserService_User_ValidateVerificationCode_Handler,
		},
		{
			MethodName: "User_GetSecurityQuestion",
			Handler:    _UserService_User_GetSecurityQuestion_Handler,
		},
		{
			MethodName: "User_ValidateSecurityAnswer",
			Handler:    _UserService_User_ValidateSecurityAnswer_Handler,
		},
		{
			MethodName: "User_ResetPassword",
			Handler:    _UserService_User_ResetPassword_Handler,
		},
		{
			MethodName: "User_GetProfile",
			Handler:    _UserService_User_GetProfile_Handler,
		},
		{
			MethodName: "User_GetUserId",
			Handler:    _UserService_User_GetUserId_Handler,
		},
		{
			MethodName: "User_ChangePassword",
			Handler:    _UserService_User_ChangePassword_Handler,
		},
		{
			MethodName: "User_UpdateProfile",
			Handler:    _UserService_User_UpdateProfile_Handler,
		},
		{
			MethodName: "User_SearchPeople",
			Handler:    _UserService_User_SearchPeople_Handler,
		},
		{
			MethodName: "User_GetSelfProfile",
			Handler:    _UserService_User_GetSelfProfile_Handler,
		},
		{
			MethodName: "User_FollowUser",
			Handler:    _UserService_User_FollowUser_Handler,
		},
		{
			MethodName: "User_BlockUser",
			Handler:    _UserService_User_BlockUser_Handler,
		},
		{
			MethodName: "User_UnFollowUser",
			Handler:    _UserService_User_UnFollowUser_Handler,
		},
		{
			MethodName: "User_UnBlockUser",
			Handler:    _UserService_User_UnBlockUser_Handler,
		},
		{
			MethodName: "User_GetSettings",
			Handler:    _UserService_User_GetSettings_Handler,
		},
		{
			MethodName: "User_UpdateSettings",
			Handler:    _UserService_User_UpdateSettings_Handler,
		},
		{
			MethodName: "User_DeactivateAccount",
			Handler:    _UserService_User_DeactivateAccount_Handler,
		},
		{
			MethodName: "User_GetAllFollowers",
			Handler:    _UserService_User_GetAllFollowers_Handler,
		},
		{
			MethodName: "User_GetAllFollowing",
			Handler:    _UserService_User_GetAllFollowing_Handler,
		},
		{
			MethodName: "User_GetAllBlocked",
			Handler:    _UserService_User_GetAllBlocked_Handler,
		},
		{
			MethodName: "User_SubmitVerifyAccountRequest",
			Handler:    _UserService_User_SubmitVerifyAccountRequest_Handler,
		},
		{
			MethodName: "User_GetAllVerifyAccountRequest",
			Handler:    _UserService_User_GetAllVerifyAccountRequest_Handler,
		},
		{
			MethodName: "User_IsUserPrivate",
			Handler:    _UserService_User_IsUserPrivate_Handler,
		},
		{
			MethodName: "User_IsUserFollowing",
			Handler:    _UserService_User_IsUserFollowing_Handler,
		},
		{
			MethodName: "User_RefreshToken",
			Handler:    _UserService_User_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
