// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: thread.proto

package thread

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThreadService_Thread_GetAllThreads_FullMethodName        = "/thread.ThreadService/Thread_GetAllThreads"
	ThreadService_Thread_GetFollowingThreads_FullMethodName  = "/thread.ThreadService/Thread_GetFollowingThreads"
	ThreadService_Thread_GetThreadById_FullMethodName        = "/thread.ThreadService/Thread_GetThreadById"
	ThreadService_Thread_SearchThreads_FullMethodName        = "/thread.ThreadService/Thread_SearchThreads"
	ThreadService_Thread_DeleteThread_FullMethodName         = "/thread.ThreadService/Thread_DeleteThread"
	ThreadService_Thread_CreateThread_FullMethodName         = "/thread.ThreadService/Thread_CreateThread"
	ThreadService_Thread_TogglePinThread_FullMethodName      = "/thread.ThreadService/Thread_TogglePinThread"
	ThreadService_Thread_VoteThread_FullMethodName           = "/thread.ThreadService/Thread_VoteThread"
	ThreadService_Thread_ToggleLike_FullMethodName           = "/thread.ThreadService/Thread_ToggleLike"
	ThreadService_Thread_ToggleBookmark_FullMethodName       = "/thread.ThreadService/Thread_ToggleBookmark"
	ThreadService_Thread_ToggleRepost_FullMethodName         = "/thread.ThreadService/Thread_ToggleRepost"
	ThreadService_Thread_GetBookmarkedThreads_FullMethodName = "/thread.ThreadService/Thread_GetBookmarkedThreads"
	ThreadService_Thread_GetRepostedThreads_FullMethodName   = "/thread.ThreadService/Thread_GetRepostedThreads"
	ThreadService_Thread_GetUserThreads_FullMethodName       = "/thread.ThreadService/Thread_GetUserThreads"
	ThreadService_Thread_GetUserLikedThreads_FullMethodName  = "/thread.ThreadService/Thread_GetUserLikedThreads"
	ThreadService_Thread_GetUserReplies_FullMethodName       = "/thread.ThreadService/Thread_GetUserReplies"
	ThreadService_Thread_GetUserMediaThreads_FullMethodName  = "/thread.ThreadService/Thread_GetUserMediaThreads"
	ThreadService_Thread_GetReplyPermission_FullMethodName   = "/thread.ThreadService/Thread_GetReplyPermission"
)

// ThreadServiceClient is the client API for ThreadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThreadServiceClient interface {
	// Protected Routes
	Thread_GetAllThreads(ctx context.Context, in *GetAllThreadsRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetFollowingThreads(ctx context.Context, in *GetAllThreadsRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetThreadById(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_SearchThreads(ctx context.Context, in *GetAllThreadsRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_DeleteThread(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_CreateThread(ctx context.Context, in *PostThread, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_TogglePinThread(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_VoteThread(ctx context.Context, in *SubmitVote, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_ToggleLike(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_ToggleBookmark(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_ToggleRepost(ctx context.Context, in *RepostRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetBookmarkedThreads(ctx context.Context, in *StringThread, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetRepostedThreads(ctx context.Context, in *StringThread, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetUserThreads(ctx context.Context, in *UserToUserRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetUserLikedThreads(ctx context.Context, in *StringThread, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetUserReplies(ctx context.Context, in *UserToUserRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetUserMediaThreads(ctx context.Context, in *UserToUserRequest, opts ...grpc.CallOption) (*ApiResponseThread, error)
	Thread_GetReplyPermission(ctx context.Context, in *StringThread, opts ...grpc.CallOption) (*ApiResponseThread, error)
}

type threadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThreadServiceClient(cc grpc.ClientConnInterface) ThreadServiceClient {
	return &threadServiceClient{cc}
}

func (c *threadServiceClient) Thread_GetAllThreads(ctx context.Context, in *GetAllThreadsRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetAllThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetFollowingThreads(ctx context.Context, in *GetAllThreadsRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetFollowingThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetThreadById(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetThreadById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_SearchThreads(ctx context.Context, in *GetAllThreadsRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_SearchThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_DeleteThread(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_DeleteThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_CreateThread(ctx context.Context, in *PostThread, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_CreateThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_TogglePinThread(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_TogglePinThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_VoteThread(ctx context.Context, in *SubmitVote, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_VoteThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_ToggleLike(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_ToggleLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_ToggleBookmark(ctx context.Context, in *GeneralThreadRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_ToggleBookmark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_ToggleRepost(ctx context.Context, in *RepostRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_ToggleRepost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetBookmarkedThreads(ctx context.Context, in *StringThread, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetBookmarkedThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetRepostedThreads(ctx context.Context, in *StringThread, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetRepostedThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetUserThreads(ctx context.Context, in *UserToUserRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetUserThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetUserLikedThreads(ctx context.Context, in *StringThread, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetUserLikedThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetUserReplies(ctx context.Context, in *UserToUserRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetUserReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetUserMediaThreads(ctx context.Context, in *UserToUserRequest, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetUserMediaThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threadServiceClient) Thread_GetReplyPermission(ctx context.Context, in *StringThread, opts ...grpc.CallOption) (*ApiResponseThread, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseThread)
	err := c.cc.Invoke(ctx, ThreadService_Thread_GetReplyPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThreadServiceServer is the server API for ThreadService service.
// All implementations must embed UnimplementedThreadServiceServer
// for forward compatibility.
type ThreadServiceServer interface {
	// Protected Routes
	Thread_GetAllThreads(context.Context, *GetAllThreadsRequest) (*ApiResponseThread, error)
	Thread_GetFollowingThreads(context.Context, *GetAllThreadsRequest) (*ApiResponseThread, error)
	Thread_GetThreadById(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error)
	Thread_SearchThreads(context.Context, *GetAllThreadsRequest) (*ApiResponseThread, error)
	Thread_DeleteThread(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error)
	Thread_CreateThread(context.Context, *PostThread) (*ApiResponseThread, error)
	Thread_TogglePinThread(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error)
	Thread_VoteThread(context.Context, *SubmitVote) (*ApiResponseThread, error)
	Thread_ToggleLike(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error)
	Thread_ToggleBookmark(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error)
	Thread_ToggleRepost(context.Context, *RepostRequest) (*ApiResponseThread, error)
	Thread_GetBookmarkedThreads(context.Context, *StringThread) (*ApiResponseThread, error)
	Thread_GetRepostedThreads(context.Context, *StringThread) (*ApiResponseThread, error)
	Thread_GetUserThreads(context.Context, *UserToUserRequest) (*ApiResponseThread, error)
	Thread_GetUserLikedThreads(context.Context, *StringThread) (*ApiResponseThread, error)
	Thread_GetUserReplies(context.Context, *UserToUserRequest) (*ApiResponseThread, error)
	Thread_GetUserMediaThreads(context.Context, *UserToUserRequest) (*ApiResponseThread, error)
	Thread_GetReplyPermission(context.Context, *StringThread) (*ApiResponseThread, error)
	mustEmbedUnimplementedThreadServiceServer()
}

// UnimplementedThreadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThreadServiceServer struct{}

func (UnimplementedThreadServiceServer) Thread_GetAllThreads(context.Context, *GetAllThreadsRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetAllThreads not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetFollowingThreads(context.Context, *GetAllThreadsRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetFollowingThreads not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetThreadById(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetThreadById not implemented")
}
func (UnimplementedThreadServiceServer) Thread_SearchThreads(context.Context, *GetAllThreadsRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_SearchThreads not implemented")
}
func (UnimplementedThreadServiceServer) Thread_DeleteThread(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_DeleteThread not implemented")
}
func (UnimplementedThreadServiceServer) Thread_CreateThread(context.Context, *PostThread) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_CreateThread not implemented")
}
func (UnimplementedThreadServiceServer) Thread_TogglePinThread(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_TogglePinThread not implemented")
}
func (UnimplementedThreadServiceServer) Thread_VoteThread(context.Context, *SubmitVote) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_VoteThread not implemented")
}
func (UnimplementedThreadServiceServer) Thread_ToggleLike(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_ToggleLike not implemented")
}
func (UnimplementedThreadServiceServer) Thread_ToggleBookmark(context.Context, *GeneralThreadRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_ToggleBookmark not implemented")
}
func (UnimplementedThreadServiceServer) Thread_ToggleRepost(context.Context, *RepostRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_ToggleRepost not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetBookmarkedThreads(context.Context, *StringThread) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetBookmarkedThreads not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetRepostedThreads(context.Context, *StringThread) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetRepostedThreads not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetUserThreads(context.Context, *UserToUserRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetUserThreads not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetUserLikedThreads(context.Context, *StringThread) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetUserLikedThreads not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetUserReplies(context.Context, *UserToUserRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetUserReplies not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetUserMediaThreads(context.Context, *UserToUserRequest) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetUserMediaThreads not implemented")
}
func (UnimplementedThreadServiceServer) Thread_GetReplyPermission(context.Context, *StringThread) (*ApiResponseThread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thread_GetReplyPermission not implemented")
}
func (UnimplementedThreadServiceServer) mustEmbedUnimplementedThreadServiceServer() {}
func (UnimplementedThreadServiceServer) testEmbeddedByValue()                       {}

// UnsafeThreadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThreadServiceServer will
// result in compilation errors.
type UnsafeThreadServiceServer interface {
	mustEmbedUnimplementedThreadServiceServer()
}

func RegisterThreadServiceServer(s grpc.ServiceRegistrar, srv ThreadServiceServer) {
	// If the following call pancis, it indicates UnimplementedThreadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThreadService_ServiceDesc, srv)
}

func _ThreadService_Thread_GetAllThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetAllThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetAllThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetAllThreads(ctx, req.(*GetAllThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetFollowingThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetFollowingThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetFollowingThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetFollowingThreads(ctx, req.(*GetAllThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetThreadById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetThreadById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetThreadById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetThreadById(ctx, req.(*GeneralThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_SearchThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_SearchThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_SearchThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_SearchThreads(ctx, req.(*GetAllThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_DeleteThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_DeleteThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_DeleteThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_DeleteThread(ctx, req.(*GeneralThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_CreateThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostThread)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_CreateThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_CreateThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_CreateThread(ctx, req.(*PostThread))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_TogglePinThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_TogglePinThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_TogglePinThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_TogglePinThread(ctx, req.(*GeneralThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_VoteThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_VoteThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_VoteThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_VoteThread(ctx, req.(*SubmitVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_ToggleLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_ToggleLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_ToggleLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_ToggleLike(ctx, req.(*GeneralThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_ToggleBookmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_ToggleBookmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_ToggleBookmark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_ToggleBookmark(ctx, req.(*GeneralThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_ToggleRepost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_ToggleRepost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_ToggleRepost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_ToggleRepost(ctx, req.(*RepostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetBookmarkedThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringThread)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetBookmarkedThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetBookmarkedThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetBookmarkedThreads(ctx, req.(*StringThread))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetRepostedThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringThread)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetRepostedThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetRepostedThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetRepostedThreads(ctx, req.(*StringThread))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetUserThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetUserThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetUserThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetUserThreads(ctx, req.(*UserToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetUserLikedThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringThread)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetUserLikedThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetUserLikedThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetUserLikedThreads(ctx, req.(*StringThread))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetUserReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetUserReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetUserReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetUserReplies(ctx, req.(*UserToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetUserMediaThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetUserMediaThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetUserMediaThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetUserMediaThreads(ctx, req.(*UserToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreadService_Thread_GetReplyPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringThread)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadServiceServer).Thread_GetReplyPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreadService_Thread_GetReplyPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadServiceServer).Thread_GetReplyPermission(ctx, req.(*StringThread))
	}
	return interceptor(ctx, in, info, handler)
}

// ThreadService_ServiceDesc is the grpc.ServiceDesc for ThreadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThreadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thread.ThreadService",
	HandlerType: (*ThreadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Thread_GetAllThreads",
			Handler:    _ThreadService_Thread_GetAllThreads_Handler,
		},
		{
			MethodName: "Thread_GetFollowingThreads",
			Handler:    _ThreadService_Thread_GetFollowingThreads_Handler,
		},
		{
			MethodName: "Thread_GetThreadById",
			Handler:    _ThreadService_Thread_GetThreadById_Handler,
		},
		{
			MethodName: "Thread_SearchThreads",
			Handler:    _ThreadService_Thread_SearchThreads_Handler,
		},
		{
			MethodName: "Thread_DeleteThread",
			Handler:    _ThreadService_Thread_DeleteThread_Handler,
		},
		{
			MethodName: "Thread_CreateThread",
			Handler:    _ThreadService_Thread_CreateThread_Handler,
		},
		{
			MethodName: "Thread_TogglePinThread",
			Handler:    _ThreadService_Thread_TogglePinThread_Handler,
		},
		{
			MethodName: "Thread_VoteThread",
			Handler:    _ThreadService_Thread_VoteThread_Handler,
		},
		{
			MethodName: "Thread_ToggleLike",
			Handler:    _ThreadService_Thread_ToggleLike_Handler,
		},
		{
			MethodName: "Thread_ToggleBookmark",
			Handler:    _ThreadService_Thread_ToggleBookmark_Handler,
		},
		{
			MethodName: "Thread_ToggleRepost",
			Handler:    _ThreadService_Thread_ToggleRepost_Handler,
		},
		{
			MethodName: "Thread_GetBookmarkedThreads",
			Handler:    _ThreadService_Thread_GetBookmarkedThreads_Handler,
		},
		{
			MethodName: "Thread_GetRepostedThreads",
			Handler:    _ThreadService_Thread_GetRepostedThreads_Handler,
		},
		{
			MethodName: "Thread_GetUserThreads",
			Handler:    _ThreadService_Thread_GetUserThreads_Handler,
		},
		{
			MethodName: "Thread_GetUserLikedThreads",
			Handler:    _ThreadService_Thread_GetUserLikedThreads_Handler,
		},
		{
			MethodName: "Thread_GetUserReplies",
			Handler:    _ThreadService_Thread_GetUserReplies_Handler,
		},
		{
			MethodName: "Thread_GetUserMediaThreads",
			Handler:    _ThreadService_Thread_GetUserMediaThreads_Handler,
		},
		{
			MethodName: "Thread_GetReplyPermission",
			Handler:    _ThreadService_Thread_GetReplyPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thread.proto",
}
