// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMessage) Reset() {
	*x = ApiResponseMessage{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMessage) ProtoMessage() {}

func (x *ApiResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMessage.ProtoReflect.Descriptor instead.
func (*ApiResponseMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponseMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApiResponseMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMessage) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type StringMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *StringMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GeneralChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralChatRequest) Reset() {
	*x = GeneralChatRequest{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralChatRequest) ProtoMessage() {}

func (x *GeneralChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralChatRequest.ProtoReflect.Descriptor instead.
func (*GeneralChatRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *GeneralChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GeneralChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GeneralMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralMessageRequest) Reset() {
	*x = GeneralMessageRequest{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralMessageRequest) ProtoMessage() {}

func (x *GeneralMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralMessageRequest.ProtoReflect.Descriptor instead.
func (*GeneralMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *GeneralMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GeneralMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GeneralMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BoolMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolMessage) Reset() {
	*x = BoolMessage{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolMessage) ProtoMessage() {}

func (x *BoolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolMessage.ProtoReflect.Descriptor instead.
func (*BoolMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *BoolMessage) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\x1a\x19google/protobuf/any.proto\"r\n" +
	"\x12ApiResponseMessage\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"%\n" +
	"\rStringMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"F\n" +
	"\x12GeneralChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\"h\n" +
	"\x15GeneralMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"#\n" +
	"\vBoolMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value2\xb3\x03\n" +
	"\x0eMessageService\x12M\n" +
	"\x16Message_GetAllMessages\x12\x16.message.StringMessage\x1a\x1b.message.ApiResponseMessage\x12U\n" +
	"\x16Message_GetMessageById\x12\x1e.message.GeneralMessageRequest\x1a\x1b.message.ApiResponseMessage\x12R\n" +
	"\x16Message_SearchMessages\x12\x1b.message.GeneralChatRequest\x1a\x1b.message.ApiResponseMessage\x12T\n" +
	"\x15Message_DeleteMessage\x12\x1e.message.GeneralMessageRequest\x1a\x1b.message.ApiResponseMessage\x12Q\n" +
	"\x12Message_ToggleLike\x12\x1e.message.GeneralMessageRequest\x1a\x1b.message.ApiResponseMessageB\n" +
	"Z\bmessage/b\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_proto_goTypes = []any{
	(*ApiResponseMessage)(nil),    // 0: message.ApiResponseMessage
	(*StringMessage)(nil),         // 1: message.StringMessage
	(*GeneralChatRequest)(nil),    // 2: message.GeneralChatRequest
	(*GeneralMessageRequest)(nil), // 3: message.GeneralMessageRequest
	(*BoolMessage)(nil),           // 4: message.BoolMessage
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
}
var file_message_proto_depIdxs = []int32{
	5, // 0: message.ApiResponseMessage.data:type_name -> google.protobuf.Any
	1, // 1: message.MessageService.Message_GetAllMessages:input_type -> message.StringMessage
	3, // 2: message.MessageService.Message_GetMessageById:input_type -> message.GeneralMessageRequest
	2, // 3: message.MessageService.Message_SearchMessages:input_type -> message.GeneralChatRequest
	3, // 4: message.MessageService.Message_DeleteMessage:input_type -> message.GeneralMessageRequest
	3, // 5: message.MessageService.Message_ToggleLike:input_type -> message.GeneralMessageRequest
	0, // 6: message.MessageService.Message_GetAllMessages:output_type -> message.ApiResponseMessage
	0, // 7: message.MessageService.Message_GetMessageById:output_type -> message.ApiResponseMessage
	0, // 8: message.MessageService.Message_SearchMessages:output_type -> message.ApiResponseMessage
	0, // 9: message.MessageService.Message_DeleteMessage:output_type -> message.ApiResponseMessage
	0, // 10: message.MessageService.Message_ToggleLike:output_type -> message.ApiResponseMessage
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
