// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_Notification_GetAllNotifications_FullMethodName    = "/user.NotificationService/Notification_GetAllNotifications"
	NotificationService_Notification_MarkNotificationAsRead_FullMethodName = "/user.NotificationService/Notification_MarkNotificationAsRead"
	NotificationService_Notification_DeleteNotification_FullMethodName     = "/user.NotificationService/Notification_DeleteNotification"
	NotificationService_Notification_ClearNotifications_FullMethodName     = "/user.NotificationService/Notification_ClearNotifications"
	NotificationService_Notification_GetSettings_FullMethodName            = "/user.NotificationService/Notification_GetSettings"
	NotificationService_Notification_UpdateSettings_FullMethodName         = "/user.NotificationService/Notification_UpdateSettings"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	// Protected Routes
	Notification_GetAllNotifications(ctx context.Context, in *GetAllNotificationsRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error)
	Notification_MarkNotificationAsRead(ctx context.Context, in *MarkNotificationAsReadRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error)
	Notification_DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error)
	Notification_ClearNotifications(ctx context.Context, in *ClearNotificationsRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error)
	Notification_GetSettings(ctx context.Context, in *GetNotificationSettingsRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error)
	Notification_UpdateSettings(ctx context.Context, in *UpdateNotificationSettingsRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) Notification_GetAllNotifications(ctx context.Context, in *GetAllNotificationsRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseNotification)
	err := c.cc.Invoke(ctx, NotificationService_Notification_GetAllNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Notification_MarkNotificationAsRead(ctx context.Context, in *MarkNotificationAsReadRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseNotification)
	err := c.cc.Invoke(ctx, NotificationService_Notification_MarkNotificationAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Notification_DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseNotification)
	err := c.cc.Invoke(ctx, NotificationService_Notification_DeleteNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Notification_ClearNotifications(ctx context.Context, in *ClearNotificationsRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseNotification)
	err := c.cc.Invoke(ctx, NotificationService_Notification_ClearNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Notification_GetSettings(ctx context.Context, in *GetNotificationSettingsRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseNotification)
	err := c.cc.Invoke(ctx, NotificationService_Notification_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Notification_UpdateSettings(ctx context.Context, in *UpdateNotificationSettingsRequest, opts ...grpc.CallOption) (*ApiResponseNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseNotification)
	err := c.cc.Invoke(ctx, NotificationService_Notification_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	// Protected Routes
	Notification_GetAllNotifications(context.Context, *GetAllNotificationsRequest) (*ApiResponseNotification, error)
	Notification_MarkNotificationAsRead(context.Context, *MarkNotificationAsReadRequest) (*ApiResponseNotification, error)
	Notification_DeleteNotification(context.Context, *DeleteNotificationRequest) (*ApiResponseNotification, error)
	Notification_ClearNotifications(context.Context, *ClearNotificationsRequest) (*ApiResponseNotification, error)
	Notification_GetSettings(context.Context, *GetNotificationSettingsRequest) (*ApiResponseNotification, error)
	Notification_UpdateSettings(context.Context, *UpdateNotificationSettingsRequest) (*ApiResponseNotification, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) Notification_GetAllNotifications(context.Context, *GetAllNotificationsRequest) (*ApiResponseNotification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notification_GetAllNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) Notification_MarkNotificationAsRead(context.Context, *MarkNotificationAsReadRequest) (*ApiResponseNotification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notification_MarkNotificationAsRead not implemented")
}
func (UnimplementedNotificationServiceServer) Notification_DeleteNotification(context.Context, *DeleteNotificationRequest) (*ApiResponseNotification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notification_DeleteNotification not implemented")
}
func (UnimplementedNotificationServiceServer) Notification_ClearNotifications(context.Context, *ClearNotificationsRequest) (*ApiResponseNotification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notification_ClearNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) Notification_GetSettings(context.Context, *GetNotificationSettingsRequest) (*ApiResponseNotification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notification_GetSettings not implemented")
}
func (UnimplementedNotificationServiceServer) Notification_UpdateSettings(context.Context, *UpdateNotificationSettingsRequest) (*ApiResponseNotification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notification_UpdateSettings not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_Notification_GetAllNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Notification_GetAllNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Notification_GetAllNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Notification_GetAllNotifications(ctx, req.(*GetAllNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Notification_MarkNotificationAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Notification_MarkNotificationAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Notification_MarkNotificationAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Notification_MarkNotificationAsRead(ctx, req.(*MarkNotificationAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Notification_DeleteNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Notification_DeleteNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Notification_DeleteNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Notification_DeleteNotification(ctx, req.(*DeleteNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Notification_ClearNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Notification_ClearNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Notification_ClearNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Notification_ClearNotifications(ctx, req.(*ClearNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Notification_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Notification_GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Notification_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Notification_GetSettings(ctx, req.(*GetNotificationSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Notification_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Notification_UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Notification_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Notification_UpdateSettings(ctx, req.(*UpdateNotificationSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notification_GetAllNotifications",
			Handler:    _NotificationService_Notification_GetAllNotifications_Handler,
		},
		{
			MethodName: "Notification_MarkNotificationAsRead",
			Handler:    _NotificationService_Notification_MarkNotificationAsRead_Handler,
		},
		{
			MethodName: "Notification_DeleteNotification",
			Handler:    _NotificationService_Notification_DeleteNotification_Handler,
		},
		{
			MethodName: "Notification_ClearNotifications",
			Handler:    _NotificationService_Notification_ClearNotifications_Handler,
		},
		{
			MethodName: "Notification_GetSettings",
			Handler:    _NotificationService_Notification_GetSettings_Handler,
		},
		{
			MethodName: "Notification_UpdateSettings",
			Handler:    _NotificationService_Notification_UpdateSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
