// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: community.proto

package community

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommunityService_Community_GetAllCommunities_FullMethodName                 = "/community.CommunityService/Community_GetAllCommunities"
	CommunityService_Community_CreateCommunity_FullMethodName                   = "/community.CommunityService/Community_CreateCommunity"
	CommunityService_Community_GetUserCommunities_FullMethodName                = "/community.CommunityService/Community_GetUserCommunities"
	CommunityService_Community_GetUserPendingCommunities_FullMethodName         = "/community.CommunityService/Community_GetUserPendingCommunities"
	CommunityService_Community_GetUserPendingApprovalCommunities_FullMethodName = "/community.CommunityService/Community_GetUserPendingApprovalCommunities"
	CommunityService_Community_GetCategories_FullMethodName                     = "/community.CommunityService/Community_GetCategories"
	CommunityService_Community_GetCommunityById_FullMethodName                  = "/community.CommunityService/Community_GetCommunityById"
	CommunityService_Community_GetCommunityMembers_FullMethodName               = "/community.CommunityService/Community_GetCommunityMembers"
	CommunityService_Community_JoinCommunity_FullMethodName                     = "/community.CommunityService/Community_JoinCommunity"
	CommunityService_Community_LeaveCommunity_FullMethodName                    = "/community.CommunityService/Community_LeaveCommunity"
	CommunityService_Community_ApproveJoinRequest_FullMethodName                = "/community.CommunityService/Community_ApproveJoinRequest"
	CommunityService_Community_DenyJoinRequest_FullMethodName                   = "/community.CommunityService/Community_DenyJoinRequest"
	CommunityService_Community_GetJoinRequests_FullMethodName                   = "/community.CommunityService/Community_GetJoinRequests"
	CommunityService_Community_DemoteMember_FullMethodName                      = "/community.CommunityService/Community_DemoteMember"
	CommunityService_Community_PromoteMember_FullMethodName                     = "/community.CommunityService/Community_PromoteMember"
	CommunityService_Admin_DeleteCategory_FullMethodName                        = "/community.CommunityService/Admin_DeleteCategory"
	CommunityService_Admin_AddCategory_FullMethodName                           = "/community.CommunityService/Admin_AddCategory"
	CommunityService_Admin_GetAllCommunityRequests_FullMethodName               = "/community.CommunityService/Admin_GetAllCommunityRequests"
	CommunityService_Admin_ApproveCommunity_FullMethodName                      = "/community.CommunityService/Admin_ApproveCommunity"
	CommunityService_Admin_RejectCommunity_FullMethodName                       = "/community.CommunityService/Admin_RejectCommunity"
)

// CommunityServiceClient is the client API for CommunityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunityServiceClient interface {
	// Protected Routes
	Community_GetAllCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_CreateCommunity(ctx context.Context, in *CreateCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_GetUserCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_GetUserPendingCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_GetUserPendingApprovalCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_GetCategories(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	Community_GetCommunityById(ctx context.Context, in *GeneralCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_GetCommunityMembers(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_JoinCommunity(ctx context.Context, in *GeneralCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_LeaveCommunity(ctx context.Context, in *GeneralCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_ApproveJoinRequest(ctx context.Context, in *GeneralModeratorRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_DenyJoinRequest(ctx context.Context, in *GeneralModeratorRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_GetJoinRequests(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_DemoteMember(ctx context.Context, in *GeneralModeratorRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Community_PromoteMember(ctx context.Context, in *GeneralModeratorRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	// Admin Routes
	Admin_DeleteCategory(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Admin_AddCategory(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Admin_GetAllCommunityRequests(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Admin_ApproveCommunity(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
	Admin_RejectCommunity(ctx context.Context, in *RejectCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error)
}

type communityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunityServiceClient(cc grpc.ClientConnInterface) CommunityServiceClient {
	return &communityServiceClient{cc}
}

func (c *communityServiceClient) Community_GetAllCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetAllCommunities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_CreateCommunity(ctx context.Context, in *CreateCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_CreateCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_GetUserCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetUserCommunities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_GetUserPendingCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetUserPendingCommunities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_GetUserPendingApprovalCommunities(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetUserPendingApprovalCommunities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_GetCategories(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_GetCommunityById(ctx context.Context, in *GeneralCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetCommunityById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_GetCommunityMembers(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetCommunityMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_JoinCommunity(ctx context.Context, in *GeneralCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_JoinCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_LeaveCommunity(ctx context.Context, in *GeneralCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_LeaveCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_ApproveJoinRequest(ctx context.Context, in *GeneralModeratorRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_ApproveJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_DenyJoinRequest(ctx context.Context, in *GeneralModeratorRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_DenyJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_GetJoinRequests(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_GetJoinRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_DemoteMember(ctx context.Context, in *GeneralModeratorRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_DemoteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Community_PromoteMember(ctx context.Context, in *GeneralModeratorRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Community_PromoteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Admin_DeleteCategory(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Admin_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Admin_AddCategory(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Admin_AddCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Admin_GetAllCommunityRequests(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Admin_GetAllCommunityRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Admin_ApproveCommunity(ctx context.Context, in *StringCommunity, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Admin_ApproveCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) Admin_RejectCommunity(ctx context.Context, in *RejectCommunityRequest, opts ...grpc.CallOption) (*ApiResponseCommunity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCommunity)
	err := c.cc.Invoke(ctx, CommunityService_Admin_RejectCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunityServiceServer is the server API for CommunityService service.
// All implementations must embed UnimplementedCommunityServiceServer
// for forward compatibility.
type CommunityServiceServer interface {
	// Protected Routes
	Community_GetAllCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Community_CreateCommunity(context.Context, *CreateCommunityRequest) (*ApiResponseCommunity, error)
	Community_GetUserCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Community_GetUserPendingCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Community_GetUserPendingApprovalCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Community_GetCategories(context.Context, *StringCommunity) (*GetCategoriesResponse, error)
	Community_GetCommunityById(context.Context, *GeneralCommunityRequest) (*ApiResponseCommunity, error)
	Community_GetCommunityMembers(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Community_JoinCommunity(context.Context, *GeneralCommunityRequest) (*ApiResponseCommunity, error)
	Community_LeaveCommunity(context.Context, *GeneralCommunityRequest) (*ApiResponseCommunity, error)
	Community_ApproveJoinRequest(context.Context, *GeneralModeratorRequest) (*ApiResponseCommunity, error)
	Community_DenyJoinRequest(context.Context, *GeneralModeratorRequest) (*ApiResponseCommunity, error)
	Community_GetJoinRequests(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Community_DemoteMember(context.Context, *GeneralModeratorRequest) (*ApiResponseCommunity, error)
	Community_PromoteMember(context.Context, *GeneralModeratorRequest) (*ApiResponseCommunity, error)
	// Admin Routes
	Admin_DeleteCategory(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Admin_AddCategory(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Admin_GetAllCommunityRequests(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Admin_ApproveCommunity(context.Context, *StringCommunity) (*ApiResponseCommunity, error)
	Admin_RejectCommunity(context.Context, *RejectCommunityRequest) (*ApiResponseCommunity, error)
	mustEmbedUnimplementedCommunityServiceServer()
}

// UnimplementedCommunityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunityServiceServer struct{}

func (UnimplementedCommunityServiceServer) Community_GetAllCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetAllCommunities not implemented")
}
func (UnimplementedCommunityServiceServer) Community_CreateCommunity(context.Context, *CreateCommunityRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_CreateCommunity not implemented")
}
func (UnimplementedCommunityServiceServer) Community_GetUserCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetUserCommunities not implemented")
}
func (UnimplementedCommunityServiceServer) Community_GetUserPendingCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetUserPendingCommunities not implemented")
}
func (UnimplementedCommunityServiceServer) Community_GetUserPendingApprovalCommunities(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetUserPendingApprovalCommunities not implemented")
}
func (UnimplementedCommunityServiceServer) Community_GetCategories(context.Context, *StringCommunity) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetCategories not implemented")
}
func (UnimplementedCommunityServiceServer) Community_GetCommunityById(context.Context, *GeneralCommunityRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetCommunityById not implemented")
}
func (UnimplementedCommunityServiceServer) Community_GetCommunityMembers(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetCommunityMembers not implemented")
}
func (UnimplementedCommunityServiceServer) Community_JoinCommunity(context.Context, *GeneralCommunityRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_JoinCommunity not implemented")
}
func (UnimplementedCommunityServiceServer) Community_LeaveCommunity(context.Context, *GeneralCommunityRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_LeaveCommunity not implemented")
}
func (UnimplementedCommunityServiceServer) Community_ApproveJoinRequest(context.Context, *GeneralModeratorRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_ApproveJoinRequest not implemented")
}
func (UnimplementedCommunityServiceServer) Community_DenyJoinRequest(context.Context, *GeneralModeratorRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_DenyJoinRequest not implemented")
}
func (UnimplementedCommunityServiceServer) Community_GetJoinRequests(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_GetJoinRequests not implemented")
}
func (UnimplementedCommunityServiceServer) Community_DemoteMember(context.Context, *GeneralModeratorRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_DemoteMember not implemented")
}
func (UnimplementedCommunityServiceServer) Community_PromoteMember(context.Context, *GeneralModeratorRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Community_PromoteMember not implemented")
}
func (UnimplementedCommunityServiceServer) Admin_DeleteCategory(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admin_DeleteCategory not implemented")
}
func (UnimplementedCommunityServiceServer) Admin_AddCategory(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admin_AddCategory not implemented")
}
func (UnimplementedCommunityServiceServer) Admin_GetAllCommunityRequests(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admin_GetAllCommunityRequests not implemented")
}
func (UnimplementedCommunityServiceServer) Admin_ApproveCommunity(context.Context, *StringCommunity) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admin_ApproveCommunity not implemented")
}
func (UnimplementedCommunityServiceServer) Admin_RejectCommunity(context.Context, *RejectCommunityRequest) (*ApiResponseCommunity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admin_RejectCommunity not implemented")
}
func (UnimplementedCommunityServiceServer) mustEmbedUnimplementedCommunityServiceServer() {}
func (UnimplementedCommunityServiceServer) testEmbeddedByValue()                          {}

// UnsafeCommunityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunityServiceServer will
// result in compilation errors.
type UnsafeCommunityServiceServer interface {
	mustEmbedUnimplementedCommunityServiceServer()
}

func RegisterCommunityServiceServer(s grpc.ServiceRegistrar, srv CommunityServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommunityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommunityService_ServiceDesc, srv)
}

func _CommunityService_Community_GetAllCommunities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetAllCommunities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetAllCommunities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetAllCommunities(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_CreateCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_CreateCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_CreateCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_CreateCommunity(ctx, req.(*CreateCommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_GetUserCommunities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetUserCommunities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetUserCommunities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetUserCommunities(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_GetUserPendingCommunities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetUserPendingCommunities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetUserPendingCommunities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetUserPendingCommunities(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_GetUserPendingApprovalCommunities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetUserPendingApprovalCommunities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetUserPendingApprovalCommunities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetUserPendingApprovalCommunities(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetCategories(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_GetCommunityById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralCommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetCommunityById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetCommunityById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetCommunityById(ctx, req.(*GeneralCommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_GetCommunityMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetCommunityMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetCommunityMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetCommunityMembers(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_JoinCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralCommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_JoinCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_JoinCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_JoinCommunity(ctx, req.(*GeneralCommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_LeaveCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralCommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_LeaveCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_LeaveCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_LeaveCommunity(ctx, req.(*GeneralCommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_ApproveJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralModeratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_ApproveJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_ApproveJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_ApproveJoinRequest(ctx, req.(*GeneralModeratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_DenyJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralModeratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_DenyJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_DenyJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_DenyJoinRequest(ctx, req.(*GeneralModeratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_GetJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_GetJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_GetJoinRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_GetJoinRequests(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_DemoteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralModeratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_DemoteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_DemoteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_DemoteMember(ctx, req.(*GeneralModeratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Community_PromoteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralModeratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Community_PromoteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Community_PromoteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Community_PromoteMember(ctx, req.(*GeneralModeratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Admin_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Admin_DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Admin_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Admin_DeleteCategory(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Admin_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Admin_AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Admin_AddCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Admin_AddCategory(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Admin_GetAllCommunityRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Admin_GetAllCommunityRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Admin_GetAllCommunityRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Admin_GetAllCommunityRequests(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Admin_ApproveCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringCommunity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Admin_ApproveCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Admin_ApproveCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Admin_ApproveCommunity(ctx, req.(*StringCommunity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_Admin_RejectCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).Admin_RejectCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_Admin_RejectCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).Admin_RejectCommunity(ctx, req.(*RejectCommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommunityService_ServiceDesc is the grpc.ServiceDesc for CommunityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommunityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.CommunityService",
	HandlerType: (*CommunityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Community_GetAllCommunities",
			Handler:    _CommunityService_Community_GetAllCommunities_Handler,
		},
		{
			MethodName: "Community_CreateCommunity",
			Handler:    _CommunityService_Community_CreateCommunity_Handler,
		},
		{
			MethodName: "Community_GetUserCommunities",
			Handler:    _CommunityService_Community_GetUserCommunities_Handler,
		},
		{
			MethodName: "Community_GetUserPendingCommunities",
			Handler:    _CommunityService_Community_GetUserPendingCommunities_Handler,
		},
		{
			MethodName: "Community_GetUserPendingApprovalCommunities",
			Handler:    _CommunityService_Community_GetUserPendingApprovalCommunities_Handler,
		},
		{
			MethodName: "Community_GetCategories",
			Handler:    _CommunityService_Community_GetCategories_Handler,
		},
		{
			MethodName: "Community_GetCommunityById",
			Handler:    _CommunityService_Community_GetCommunityById_Handler,
		},
		{
			MethodName: "Community_GetCommunityMembers",
			Handler:    _CommunityService_Community_GetCommunityMembers_Handler,
		},
		{
			MethodName: "Community_JoinCommunity",
			Handler:    _CommunityService_Community_JoinCommunity_Handler,
		},
		{
			MethodName: "Community_LeaveCommunity",
			Handler:    _CommunityService_Community_LeaveCommunity_Handler,
		},
		{
			MethodName: "Community_ApproveJoinRequest",
			Handler:    _CommunityService_Community_ApproveJoinRequest_Handler,
		},
		{
			MethodName: "Community_DenyJoinRequest",
			Handler:    _CommunityService_Community_DenyJoinRequest_Handler,
		},
		{
			MethodName: "Community_GetJoinRequests",
			Handler:    _CommunityService_Community_GetJoinRequests_Handler,
		},
		{
			MethodName: "Community_DemoteMember",
			Handler:    _CommunityService_Community_DemoteMember_Handler,
		},
		{
			MethodName: "Community_PromoteMember",
			Handler:    _CommunityService_Community_PromoteMember_Handler,
		},
		{
			MethodName: "Admin_DeleteCategory",
			Handler:    _CommunityService_Admin_DeleteCategory_Handler,
		},
		{
			MethodName: "Admin_AddCategory",
			Handler:    _CommunityService_Admin_AddCategory_Handler,
		},
		{
			MethodName: "Admin_GetAllCommunityRequests",
			Handler:    _CommunityService_Admin_GetAllCommunityRequests_Handler,
		},
		{
			MethodName: "Admin_ApproveCommunity",
			Handler:    _CommunityService_Admin_ApproveCommunity_Handler,
		},
		{
			MethodName: "Admin_RejectCommunity",
			Handler:    _CommunityService_Admin_RejectCommunity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "community.proto",
}
