// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: community.proto

package community

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponseCommunity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCommunity) Reset() {
	*x = ApiResponseCommunity{}
	mi := &file_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCommunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCommunity) ProtoMessage() {}

func (x *ApiResponseCommunity) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCommunity.ProtoReflect.Descriptor instead.
func (*ApiResponseCommunity) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponseCommunity) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApiResponseCommunity) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCommunity) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type StringCommunity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringCommunity) Reset() {
	*x = StringCommunity{}
	mi := &file_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringCommunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringCommunity) ProtoMessage() {}

func (x *StringCommunity) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringCommunity.ProtoReflect.Descriptor instead.
func (*StringCommunity) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{1}
}

func (x *StringCommunity) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GeneralCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralCommunityRequest) Reset() {
	*x = GeneralCommunityRequest{}
	mi := &file_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralCommunityRequest) ProtoMessage() {}

func (x *GeneralCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralCommunityRequest.ProtoReflect.Descriptor instead.
func (*GeneralCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{2}
}

func (x *GeneralCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *GeneralCommunityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GeneralModeratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModeratorId   string                 `protobuf:"bytes,3,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralModeratorRequest) Reset() {
	*x = GeneralModeratorRequest{}
	mi := &file_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralModeratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralModeratorRequest) ProtoMessage() {}

func (x *GeneralModeratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralModeratorRequest.ProtoReflect.Descriptor instead.
func (*GeneralModeratorRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{3}
}

func (x *GeneralModeratorRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *GeneralModeratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GeneralModeratorRequest) GetModeratorId() string {
	if x != nil {
		return x.ModeratorId
	}
	return ""
}

type BoolCommunity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolCommunity) Reset() {
	*x = BoolCommunity{}
	mi := &file_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolCommunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolCommunity) ProtoMessage() {}

func (x *BoolCommunity) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolCommunity.ProtoReflect.Descriptor instead.
func (*BoolCommunity) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{4}
}

func (x *BoolCommunity) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type CommunityMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityMember) Reset() {
	*x = CommunityMember{}
	mi := &file_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityMember) ProtoMessage() {}

func (x *CommunityMember) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityMember.ProtoReflect.Descriptor instead.
func (*CommunityMember) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{5}
}

func (x *CommunityMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommunityMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*CommunityMember     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	mi := &file_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{6}
}

func (x *GetMembersResponse) GetMembers() []*CommunityMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type RejectCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectCommunityRequest) Reset() {
	*x = RejectCommunityRequest{}
	mi := &file_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectCommunityRequest) ProtoMessage() {}

func (x *RejectCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectCommunityRequest.ProtoReflect.Descriptor instead.
func (*RejectCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{7}
}

func (x *RejectCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *RejectCommunityRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetCommunitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []*Community           `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunitiesResponse) Reset() {
	*x = GetCommunitiesResponse{}
	mi := &file_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunitiesResponse) ProtoMessage() {}

func (x *GetCommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommunitiesResponse) GetCommunities() []*Community {
	if x != nil {
		return x.Communities
	}
	return nil
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{9}
}

func (x *GetCategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Community struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	CommunityName string                 `protobuf:"bytes,2,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Categories    []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Rules         string                 `protobuf:"bytes,6,opt,name=rules,proto3" json:"rules,omitempty"`
	CreatorId     string                 `protobuf:"bytes,7,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	BannerImage   string                 `protobuf:"bytes,8,opt,name=banner_image,json=bannerImage,proto3" json:"banner_image,omitempty"`
	IconImage     string                 `protobuf:"bytes,9,opt,name=icon_image,json=iconImage,proto3" json:"icon_image,omitempty"`
	MemberCount   int32                  `protobuf:"varint,10,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	Role          string                 `protobuf:"bytes,11,opt,name=role,proto3" json:"role,omitempty"`
	IsPending     bool                   `protobuf:"varint,12,opt,name=is_pending,json=isPending,proto3" json:"is_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Community) Reset() {
	*x = Community{}
	mi := &file_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Community) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Community) ProtoMessage() {}

func (x *Community) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Community.ProtoReflect.Descriptor instead.
func (*Community) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{10}
}

func (x *Community) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *Community) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

func (x *Community) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Community) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Community) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Community) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *Community) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Community) GetBannerImage() string {
	if x != nil {
		return x.BannerImage
	}
	return ""
}

func (x *Community) GetIconImage() string {
	if x != nil {
		return x.IconImage
	}
	return ""
}

func (x *Community) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Community) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Community) GetIsPending() bool {
	if x != nil {
		return x.IsPending
	}
	return false
}

type CreateCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityName string                 `protobuf:"bytes,1,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Categories    []string               `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rules         string                 `protobuf:"bytes,5,opt,name=rules,proto3" json:"rules,omitempty"`
	CommunityId   string                 `protobuf:"bytes,6,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	BannerImage   string                 `protobuf:"bytes,7,opt,name=banner_image,json=bannerImage,proto3" json:"banner_image,omitempty"`
	IconImage     string                 `protobuf:"bytes,8,opt,name=icon_image,json=iconImage,proto3" json:"icon_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommunityRequest) Reset() {
	*x = CreateCommunityRequest{}
	mi := &file_community_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommunityRequest) ProtoMessage() {}

func (x *CreateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommunityRequest.ProtoReflect.Descriptor instead.
func (*CreateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCommunityRequest) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

func (x *CreateCommunityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCommunityRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CreateCommunityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCommunityRequest) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *CreateCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *CreateCommunityRequest) GetBannerImage() string {
	if x != nil {
		return x.BannerImage
	}
	return ""
}

func (x *CreateCommunityRequest) GetIconImage() string {
	if x != nil {
		return x.IconImage
	}
	return ""
}

type CommunityCategories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityCategories) Reset() {
	*x = CommunityCategories{}
	mi := &file_community_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityCategories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCategories) ProtoMessage() {}

func (x *CommunityCategories) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCategories.ProtoReflect.Descriptor instead.
func (*CommunityCategories) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{12}
}

func (x *CommunityCategories) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_community_proto protoreflect.FileDescriptor

const file_community_proto_rawDesc = "" +
	"\n" +
	"\x0fcommunity.proto\x12\tcommunity\x1a\x19google/protobuf/any.proto\"t\n" +
	"\x14ApiResponseCommunity\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"'\n" +
	"\x0fStringCommunity\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"U\n" +
	"\x17GeneralCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"x\n" +
	"\x17GeneralModeratorRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fmoderator_id\x18\x03 \x01(\tR\vmoderatorId\"%\n" +
	"\rBoolCommunity\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\">\n" +
	"\x0fCommunityMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"J\n" +
	"\x12GetMembersResponse\x124\n" +
	"\amembers\x18\x01 \x03(\v2\x1a.community.CommunityMemberR\amembers\"S\n" +
	"\x16RejectCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"P\n" +
	"\x16GetCommunitiesResponse\x126\n" +
	"\vcommunities\x18\x01 \x03(\v2\x14.community.CommunityR\vcommunities\"7\n" +
	"\x15GetCategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"\x83\x03\n" +
	"\tCommunity\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12%\n" +
	"\x0ecommunity_name\x18\x02 \x01(\tR\rcommunityName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05rules\x18\x06 \x01(\tR\x05rules\x12\x1d\n" +
	"\n" +
	"creator_id\x18\a \x01(\tR\tcreatorId\x12!\n" +
	"\fbanner_image\x18\b \x01(\tR\vbannerImage\x12\x1d\n" +
	"\n" +
	"icon_image\x18\t \x01(\tR\ticonImage\x12!\n" +
	"\fmember_count\x18\n" +
	" \x01(\x05R\vmemberCount\x12\x12\n" +
	"\x04role\x18\v \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"is_pending\x18\f \x01(\bR\tisPending\"\x95\x02\n" +
	"\x16CreateCommunityRequest\x12%\n" +
	"\x0ecommunity_name\x18\x01 \x01(\tR\rcommunityName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x14\n" +
	"\x05rules\x18\x05 \x01(\tR\x05rules\x12!\n" +
	"\fcommunity_id\x18\x06 \x01(\tR\vcommunityId\x12!\n" +
	"\fbanner_image\x18\a \x01(\tR\vbannerImage\x12\x1d\n" +
	"\n" +
	"icon_image\x18\b \x01(\tR\ticonImage\"5\n" +
	"\x13CommunityCategories\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories2\xf0\x0e\n" +
	"\x10CommunityService\x12Z\n" +
	"\x1bCommunity_GetAllCommunities\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12_\n" +
	"\x19Community_CreateCommunity\x12!.community.CreateCommunityRequest\x1a\x1f.community.ApiResponseCommunity\x12[\n" +
	"\x1cCommunity_GetUserCommunities\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12b\n" +
	"#Community_GetUserPendingCommunities\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12j\n" +
	"+Community_GetUserPendingApprovalCommunities\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12W\n" +
	"\x17Community_GetCategories\x12\x1a.community.StringCommunity\x1a .community.GetCategoriesResponse\x12a\n" +
	"\x1aCommunity_GetCommunityById\x12\".community.GeneralCommunityRequest\x1a\x1f.community.ApiResponseCommunity\x12\\\n" +
	"\x1dCommunity_GetCommunityMembers\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12^\n" +
	"\x17Community_JoinCommunity\x12\".community.GeneralCommunityRequest\x1a\x1f.community.ApiResponseCommunity\x12_\n" +
	"\x18Community_LeaveCommunity\x12\".community.GeneralCommunityRequest\x1a\x1f.community.ApiResponseCommunity\x12c\n" +
	"\x1cCommunity_ApproveJoinRequest\x12\".community.GeneralModeratorRequest\x1a\x1f.community.ApiResponseCommunity\x12`\n" +
	"\x19Community_DenyJoinRequest\x12\".community.GeneralModeratorRequest\x1a\x1f.community.ApiResponseCommunity\x12X\n" +
	"\x19Community_GetJoinRequests\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12]\n" +
	"\x16Community_DemoteMember\x12\".community.GeneralModeratorRequest\x1a\x1f.community.ApiResponseCommunity\x12^\n" +
	"\x17Community_PromoteMember\x12\".community.GeneralModeratorRequest\x1a\x1f.community.ApiResponseCommunity\x12S\n" +
	"\x14Admin_DeleteCategory\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12P\n" +
	"\x11Admin_AddCategory\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12\\\n" +
	"\x1dAdmin_GetAllCommunityRequests\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12U\n" +
	"\x16Admin_ApproveCommunity\x12\x1a.community.StringCommunity\x1a\x1f.community.ApiResponseCommunity\x12[\n" +
	"\x15Admin_RejectCommunity\x12!.community.RejectCommunityRequest\x1a\x1f.community.ApiResponseCommunityB\fZ\n" +
	"community/b\x06proto3"

var (
	file_community_proto_rawDescOnce sync.Once
	file_community_proto_rawDescData []byte
)

func file_community_proto_rawDescGZIP() []byte {
	file_community_proto_rawDescOnce.Do(func() {
		file_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_proto_rawDesc), len(file_community_proto_rawDesc)))
	})
	return file_community_proto_rawDescData
}

var file_community_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_community_proto_goTypes = []any{
	(*ApiResponseCommunity)(nil),    // 0: community.ApiResponseCommunity
	(*StringCommunity)(nil),         // 1: community.StringCommunity
	(*GeneralCommunityRequest)(nil), // 2: community.GeneralCommunityRequest
	(*GeneralModeratorRequest)(nil), // 3: community.GeneralModeratorRequest
	(*BoolCommunity)(nil),           // 4: community.BoolCommunity
	(*CommunityMember)(nil),         // 5: community.CommunityMember
	(*GetMembersResponse)(nil),      // 6: community.GetMembersResponse
	(*RejectCommunityRequest)(nil),  // 7: community.RejectCommunityRequest
	(*GetCommunitiesResponse)(nil),  // 8: community.GetCommunitiesResponse
	(*GetCategoriesResponse)(nil),   // 9: community.GetCategoriesResponse
	(*Community)(nil),               // 10: community.Community
	(*CreateCommunityRequest)(nil),  // 11: community.CreateCommunityRequest
	(*CommunityCategories)(nil),     // 12: community.CommunityCategories
	(*anypb.Any)(nil),               // 13: google.protobuf.Any
}
var file_community_proto_depIdxs = []int32{
	13, // 0: community.ApiResponseCommunity.data:type_name -> google.protobuf.Any
	5,  // 1: community.GetMembersResponse.members:type_name -> community.CommunityMember
	10, // 2: community.GetCommunitiesResponse.communities:type_name -> community.Community
	1,  // 3: community.CommunityService.Community_GetAllCommunities:input_type -> community.StringCommunity
	11, // 4: community.CommunityService.Community_CreateCommunity:input_type -> community.CreateCommunityRequest
	1,  // 5: community.CommunityService.Community_GetUserCommunities:input_type -> community.StringCommunity
	1,  // 6: community.CommunityService.Community_GetUserPendingCommunities:input_type -> community.StringCommunity
	1,  // 7: community.CommunityService.Community_GetUserPendingApprovalCommunities:input_type -> community.StringCommunity
	1,  // 8: community.CommunityService.Community_GetCategories:input_type -> community.StringCommunity
	2,  // 9: community.CommunityService.Community_GetCommunityById:input_type -> community.GeneralCommunityRequest
	1,  // 10: community.CommunityService.Community_GetCommunityMembers:input_type -> community.StringCommunity
	2,  // 11: community.CommunityService.Community_JoinCommunity:input_type -> community.GeneralCommunityRequest
	2,  // 12: community.CommunityService.Community_LeaveCommunity:input_type -> community.GeneralCommunityRequest
	3,  // 13: community.CommunityService.Community_ApproveJoinRequest:input_type -> community.GeneralModeratorRequest
	3,  // 14: community.CommunityService.Community_DenyJoinRequest:input_type -> community.GeneralModeratorRequest
	1,  // 15: community.CommunityService.Community_GetJoinRequests:input_type -> community.StringCommunity
	3,  // 16: community.CommunityService.Community_DemoteMember:input_type -> community.GeneralModeratorRequest
	3,  // 17: community.CommunityService.Community_PromoteMember:input_type -> community.GeneralModeratorRequest
	1,  // 18: community.CommunityService.Admin_DeleteCategory:input_type -> community.StringCommunity
	1,  // 19: community.CommunityService.Admin_AddCategory:input_type -> community.StringCommunity
	1,  // 20: community.CommunityService.Admin_GetAllCommunityRequests:input_type -> community.StringCommunity
	1,  // 21: community.CommunityService.Admin_ApproveCommunity:input_type -> community.StringCommunity
	7,  // 22: community.CommunityService.Admin_RejectCommunity:input_type -> community.RejectCommunityRequest
	0,  // 23: community.CommunityService.Community_GetAllCommunities:output_type -> community.ApiResponseCommunity
	0,  // 24: community.CommunityService.Community_CreateCommunity:output_type -> community.ApiResponseCommunity
	0,  // 25: community.CommunityService.Community_GetUserCommunities:output_type -> community.ApiResponseCommunity
	0,  // 26: community.CommunityService.Community_GetUserPendingCommunities:output_type -> community.ApiResponseCommunity
	0,  // 27: community.CommunityService.Community_GetUserPendingApprovalCommunities:output_type -> community.ApiResponseCommunity
	9,  // 28: community.CommunityService.Community_GetCategories:output_type -> community.GetCategoriesResponse
	0,  // 29: community.CommunityService.Community_GetCommunityById:output_type -> community.ApiResponseCommunity
	0,  // 30: community.CommunityService.Community_GetCommunityMembers:output_type -> community.ApiResponseCommunity
	0,  // 31: community.CommunityService.Community_JoinCommunity:output_type -> community.ApiResponseCommunity
	0,  // 32: community.CommunityService.Community_LeaveCommunity:output_type -> community.ApiResponseCommunity
	0,  // 33: community.CommunityService.Community_ApproveJoinRequest:output_type -> community.ApiResponseCommunity
	0,  // 34: community.CommunityService.Community_DenyJoinRequest:output_type -> community.ApiResponseCommunity
	0,  // 35: community.CommunityService.Community_GetJoinRequests:output_type -> community.ApiResponseCommunity
	0,  // 36: community.CommunityService.Community_DemoteMember:output_type -> community.ApiResponseCommunity
	0,  // 37: community.CommunityService.Community_PromoteMember:output_type -> community.ApiResponseCommunity
	0,  // 38: community.CommunityService.Admin_DeleteCategory:output_type -> community.ApiResponseCommunity
	0,  // 39: community.CommunityService.Admin_AddCategory:output_type -> community.ApiResponseCommunity
	0,  // 40: community.CommunityService.Admin_GetAllCommunityRequests:output_type -> community.ApiResponseCommunity
	0,  // 41: community.CommunityService.Admin_ApproveCommunity:output_type -> community.ApiResponseCommunity
	0,  // 42: community.CommunityService.Admin_RejectCommunity:output_type -> community.ApiResponseCommunity
	23, // [23:43] is the sub-list for method output_type
	3,  // [3:23] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_community_proto_init() }
func file_community_proto_init() {
	if File_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_proto_rawDesc), len(file_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_proto_goTypes,
		DependencyIndexes: file_community_proto_depIdxs,
		MessageInfos:      file_community_proto_msgTypes,
	}.Build()
	File_community_proto = out.File
	file_community_proto_goTypes = nil
	file_community_proto_depIdxs = nil
}
