// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: thread.proto

package thread

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponseThread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseThread) Reset() {
	*x = ApiResponseThread{}
	mi := &file_thread_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseThread) ProtoMessage() {}

func (x *ApiResponseThread) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseThread.ProtoReflect.Descriptor instead.
func (*ApiResponseThread) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponseThread) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApiResponseThread) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseThread) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchThreadRequest) Reset() {
	*x = SearchThreadRequest{}
	mi := &file_thread_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchThreadRequest) ProtoMessage() {}

func (x *SearchThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchThreadRequest.ProtoReflect.Descriptor instead.
func (*SearchThreadRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{1}
}

func (x *SearchThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchThreadRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type StringThread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringThread) Reset() {
	*x = StringThread{}
	mi := &file_thread_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringThread) ProtoMessage() {}

func (x *StringThread) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringThread.ProtoReflect.Descriptor instead.
func (*StringThread) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{2}
}

func (x *StringThread) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SubmitVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVote) Reset() {
	*x = SubmitVote{}
	mi := &file_thread_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVote) ProtoMessage() {}

func (x *SubmitVote) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVote.ProtoReflect.Descriptor instead.
func (*SubmitVote) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitVote) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitVote) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SubmitVote) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReplyThread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	OptionId      string                 `protobuf:"bytes,3,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyThread) Reset() {
	*x = ReplyThread{}
	mi := &file_thread_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyThread) ProtoMessage() {}

func (x *ReplyThread) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyThread.ProtoReflect.Descriptor instead.
func (*ReplyThread) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{4}
}

func (x *ReplyThread) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReplyThread) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ReplyThread) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

type GeneralThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralThreadRequest) Reset() {
	*x = GeneralThreadRequest{}
	mi := &file_thread_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralThreadRequest) ProtoMessage() {}

func (x *GeneralThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralThreadRequest.ProtoReflect.Descriptor instead.
func (*GeneralThreadRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{5}
}

func (x *GeneralThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GeneralThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type Thread struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ThreadId        string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	IsAdvertisement bool                   `protobuf:"varint,5,opt,name=is_advertisement,json=isAdvertisement,proto3" json:"is_advertisement,omitempty"`
	ReplyPermission string                 `protobuf:"bytes,6,opt,name=reply_permission,json=replyPermission,proto3" json:"reply_permission,omitempty"`
	Pinned          bool                   `protobuf:"varint,7,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Media           []*Media               `protobuf:"bytes,8,rep,name=media,proto3" json:"media,omitempty"`
	PollOptions     []*PollOption          `protobuf:"bytes,9,rep,name=poll_options,json=pollOptions,proto3" json:"poll_options,omitempty"`
	LikeCount       int32                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	RepostCount     int32                  `protobuf:"varint,11,opt,name=repost_count,json=repostCount,proto3" json:"repost_count,omitempty"`
	ReplyCount      int32                  `protobuf:"varint,12,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	PostedAt        string                 `protobuf:"bytes,13,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	IsPrivate       bool                   `protobuf:"varint,14,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	IsLiking        bool                   `protobuf:"varint,15,opt,name=is_liking,json=isLiking,proto3" json:"is_liking,omitempty"`
	IsBookmarking   bool                   `protobuf:"varint,16,opt,name=is_bookmarking,json=isBookmarking,proto3" json:"is_bookmarking,omitempty"`
	IsReposting     bool                   `protobuf:"varint,17,opt,name=is_reposting,json=isReposting,proto3" json:"is_reposting,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_thread_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{6}
}

func (x *Thread) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Thread) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Thread) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Thread) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Thread) GetIsAdvertisement() bool {
	if x != nil {
		return x.IsAdvertisement
	}
	return false
}

func (x *Thread) GetReplyPermission() string {
	if x != nil {
		return x.ReplyPermission
	}
	return ""
}

func (x *Thread) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *Thread) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Thread) GetPollOptions() []*PollOption {
	if x != nil {
		return x.PollOptions
	}
	return nil
}

func (x *Thread) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Thread) GetRepostCount() int32 {
	if x != nil {
		return x.RepostCount
	}
	return 0
}

func (x *Thread) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Thread) GetPostedAt() string {
	if x != nil {
		return x.PostedAt
	}
	return ""
}

func (x *Thread) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Thread) GetIsLiking() bool {
	if x != nil {
		return x.IsLiking
	}
	return false
}

func (x *Thread) GetIsBookmarking() bool {
	if x != nil {
		return x.IsBookmarking
	}
	return false
}

func (x *Thread) GetIsReposting() bool {
	if x != nil {
		return x.IsReposting
	}
	return false
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_thread_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{7}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Media) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type PollOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Option        string                 `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	VoteCount     int32                  `protobuf:"varint,3,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOption) Reset() {
	*x = PollOption{}
	mi := &file_thread_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOption) ProtoMessage() {}

func (x *PollOption) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOption.ProtoReflect.Descriptor instead.
func (*PollOption) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{8}
}

func (x *PollOption) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *PollOption) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *PollOption) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

type ThreadLike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadLike) Reset() {
	*x = ThreadLike{}
	mi := &file_thread_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadLike) ProtoMessage() {}

func (x *ThreadLike) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadLike.ProtoReflect.Descriptor instead.
func (*ThreadLike) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{9}
}

func (x *ThreadLike) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThreadLike) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ThreadRepost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadRepost) Reset() {
	*x = ThreadRepost{}
	mi := &file_thread_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadRepost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadRepost) ProtoMessage() {}

func (x *ThreadRepost) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadRepost.ProtoReflect.Descriptor instead.
func (*ThreadRepost) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{10}
}

func (x *ThreadRepost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThreadRepost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadRepost) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ThreadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsPinned      bool                   `protobuf:"varint,4,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadReply) Reset() {
	*x = ThreadReply{}
	mi := &file_thread_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadReply) ProtoMessage() {}

func (x *ThreadReply) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadReply.ProtoReflect.Descriptor instead.
func (*ThreadReply) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{11}
}

func (x *ThreadReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThreadReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ThreadReply) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

type GetAllThreadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllThreadsRequest) Reset() {
	*x = GetAllThreadsRequest{}
	mi := &file_thread_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllThreadsRequest) ProtoMessage() {}

func (x *GetAllThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllThreadsRequest.ProtoReflect.Descriptor instead.
func (*GetAllThreadsRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllThreadsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetThreadsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadsByUserRequest) Reset() {
	*x = GetThreadsByUserRequest{}
	mi := &file_thread_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadsByUserRequest) ProtoMessage() {}

func (x *GetThreadsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetThreadsByUserRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{13}
}

func (x *GetThreadsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetThreadsByUserRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type GetThreadsByCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadsByCommunityRequest) Reset() {
	*x = GetThreadsByCommunityRequest{}
	mi := &file_thread_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadsByCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadsByCommunityRequest) ProtoMessage() {}

func (x *GetThreadsByCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadsByCommunityRequest.ProtoReflect.Descriptor instead.
func (*GetThreadsByCommunityRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{14}
}

func (x *GetThreadsByCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *GetThreadsByCommunityRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type PostThread struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsCommunity     bool                   `protobuf:"varint,2,opt,name=is_community,json=isCommunity,proto3" json:"is_community,omitempty"`
	CommunityId     string                 `protobuf:"bytes,3,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	PollCount       int32                  `protobuf:"varint,4,opt,name=poll_count,json=pollCount,proto3" json:"poll_count,omitempty"`
	PollOptions     []string               `protobuf:"bytes,5,rep,name=poll_options,json=pollOptions,proto3" json:"poll_options,omitempty"`
	MediaCount      int32                  `protobuf:"varint,56,opt,name=media_count,json=mediaCount,proto3" json:"media_count,omitempty"`
	MediaUrls       []string               `protobuf:"bytes,7,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	IsScheduled     bool                   `protobuf:"varint,8,opt,name=is_scheduled,json=isScheduled,proto3" json:"is_scheduled,omitempty"`
	ScheduledAt     string                 `protobuf:"bytes,9,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	ReplyPermission string                 `protobuf:"bytes,10,opt,name=reply_permission,json=replyPermission,proto3" json:"reply_permission,omitempty"`
	IsAdvertisement bool                   `protobuf:"varint,11,opt,name=is_advertisement,json=isAdvertisement,proto3" json:"is_advertisement,omitempty"`
	IsPrivate       bool                   `protobuf:"varint,12,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Content         string                 `protobuf:"bytes,13,opt,name=content,proto3" json:"content,omitempty"`
	Title           string                 `protobuf:"bytes,14,opt,name=title,proto3" json:"title,omitempty"`
	Category        string                 `protobuf:"bytes,15,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PostThread) Reset() {
	*x = PostThread{}
	mi := &file_thread_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostThread) ProtoMessage() {}

func (x *PostThread) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostThread.ProtoReflect.Descriptor instead.
func (*PostThread) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{15}
}

func (x *PostThread) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostThread) GetIsCommunity() bool {
	if x != nil {
		return x.IsCommunity
	}
	return false
}

func (x *PostThread) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *PostThread) GetPollCount() int32 {
	if x != nil {
		return x.PollCount
	}
	return 0
}

func (x *PostThread) GetPollOptions() []string {
	if x != nil {
		return x.PollOptions
	}
	return nil
}

func (x *PostThread) GetMediaCount() int32 {
	if x != nil {
		return x.MediaCount
	}
	return 0
}

func (x *PostThread) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *PostThread) GetIsScheduled() bool {
	if x != nil {
		return x.IsScheduled
	}
	return false
}

func (x *PostThread) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

func (x *PostThread) GetReplyPermission() string {
	if x != nil {
		return x.ReplyPermission
	}
	return ""
}

func (x *PostThread) GetIsAdvertisement() bool {
	if x != nil {
		return x.IsAdvertisement
	}
	return false
}

func (x *PostThread) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *PostThread) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostThread) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostThread) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*Thread              `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadsResponse) Reset() {
	*x = GetThreadsResponse{}
	mi := &file_thread_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadsResponse) ProtoMessage() {}

func (x *GetThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadsResponse.ProtoReflect.Descriptor instead.
func (*GetThreadsResponse) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{16}
}

func (x *GetThreadsResponse) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

type DeleteThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreadRequest) Reset() {
	*x = DeleteThreadRequest{}
	mi := &file_thread_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreadRequest) ProtoMessage() {}

func (x *DeleteThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteThreadRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type RepostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepostRequest) Reset() {
	*x = RepostRequest{}
	mi := &file_thread_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostRequest) ProtoMessage() {}

func (x *RepostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thread_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostRequest.ProtoReflect.Descriptor instead.
func (*RepostRequest) Descriptor() ([]byte, []int) {
	return file_thread_proto_rawDescGZIP(), []int{18}
}

func (x *RepostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RepostRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *RepostRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_thread_proto protoreflect.FileDescriptor

const file_thread_proto_rawDesc = "" +
	"\n" +
	"\fthread.proto\x12\x06thread\x1a\x19google/protobuf/any.proto\"q\n" +
	"\x11ApiResponseThread\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"D\n" +
	"\x13SearchThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"$\n" +
	"\fStringThread\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\\\n" +
	"\n" +
	"SubmitVote\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"`\n" +
	"\vReplyThread\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x1b\n" +
	"\toption_id\x18\x03 \x01(\tR\boptionId\"L\n" +
	"\x14GeneralThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"\xc4\x04\n" +
	"\x06Thread\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12)\n" +
	"\x10is_advertisement\x18\x05 \x01(\bR\x0fisAdvertisement\x12)\n" +
	"\x10reply_permission\x18\x06 \x01(\tR\x0freplyPermission\x12\x16\n" +
	"\x06pinned\x18\a \x01(\bR\x06pinned\x12#\n" +
	"\x05media\x18\b \x03(\v2\r.thread.MediaR\x05media\x125\n" +
	"\fpoll_options\x18\t \x03(\v2\x12.thread.PollOptionR\vpollOptions\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x05R\tlikeCount\x12!\n" +
	"\frepost_count\x18\v \x01(\x05R\vrepostCount\x12\x1f\n" +
	"\vreply_count\x18\f \x01(\x05R\n" +
	"replyCount\x12\x1b\n" +
	"\tposted_at\x18\r \x01(\tR\bpostedAt\x12\x1d\n" +
	"\n" +
	"is_private\x18\x0e \x01(\bR\tisPrivate\x12\x1b\n" +
	"\tis_liking\x18\x0f \x01(\bR\bisLiking\x12%\n" +
	"\x0eis_bookmarking\x18\x10 \x01(\bR\risBookmarking\x12!\n" +
	"\fis_reposting\x18\x11 \x01(\bR\visReposting\"S\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"`\n" +
	"\n" +
	"PollOption\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x16\n" +
	"\x06option\x18\x02 \x01(\tR\x06option\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x03 \x01(\x05R\tvoteCount\"5\n" +
	"\n" +
	"ThreadLike\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\fThreadRepost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"m\n" +
	"\vThreadReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tis_pinned\x18\x04 \x01(\bR\bisPinned\"/\n" +
	"\x14GetAllThreadsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\x17GetThreadsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\"d\n" +
	"\x1cGetThreadsByCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\"\xf4\x03\n" +
	"\n" +
	"PostThread\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fis_community\x18\x02 \x01(\bR\visCommunity\x12!\n" +
	"\fcommunity_id\x18\x03 \x01(\tR\vcommunityId\x12\x1d\n" +
	"\n" +
	"poll_count\x18\x04 \x01(\x05R\tpollCount\x12!\n" +
	"\fpoll_options\x18\x05 \x03(\tR\vpollOptions\x12\x1f\n" +
	"\vmedia_count\x188 \x01(\x05R\n" +
	"mediaCount\x12\x1d\n" +
	"\n" +
	"media_urls\x18\a \x03(\tR\tmediaUrls\x12!\n" +
	"\fis_scheduled\x18\b \x01(\bR\visScheduled\x12!\n" +
	"\fscheduled_at\x18\t \x01(\tR\vscheduledAt\x12)\n" +
	"\x10reply_permission\x18\n" +
	" \x01(\tR\x0freplyPermission\x12)\n" +
	"\x10is_advertisement\x18\v \x01(\bR\x0fisAdvertisement\x12\x1d\n" +
	"\n" +
	"is_private\x18\f \x01(\bR\tisPrivate\x12\x18\n" +
	"\acontent\x18\r \x01(\tR\acontent\x12\x14\n" +
	"\x05title\x18\x0e \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x0f \x01(\tR\bcategory\">\n" +
	"\x12GetThreadsResponse\x12(\n" +
	"\athreads\x18\x01 \x03(\v2\x0e.thread.ThreadR\athreads\"K\n" +
	"\x13DeleteThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"Y\n" +
	"\rRepostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text2\x9d\v\n" +
	"\rThreadService\x12O\n" +
	"\x14Thread_GetAllThreads\x12\x1c.thread.GetAllThreadsRequest\x1a\x19.thread.ApiResponseThread\x12O\n" +
	"\x14Thread_SearchThreads\x12\x1c.thread.GetAllThreadsRequest\x1a\x19.thread.ApiResponseThread\x12M\n" +
	"\x13Thread_DeleteThread\x12\x1b.thread.DeleteThreadRequest\x1a\x19.thread.ApiResponseThread\x12D\n" +
	"\x13Thread_CreateThread\x12\x12.thread.PostThread\x1a\x19.thread.ApiResponseThread\x12K\n" +
	"\x10Thread_PinThread\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12M\n" +
	"\x12Thread_UnPinThread\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12B\n" +
	"\x11Thread_VoteThread\x12\x12.thread.SubmitVote\x1a\x19.thread.ApiResponseThread\x12L\n" +
	"\x11Thread_ToggleLike\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12P\n" +
	"\x15Thread_ToggleBookmark\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12G\n" +
	"\x13Thread_ToggleRepost\x12\x15.thread.RepostRequest\x1a\x19.thread.ApiResponseThread\x12M\n" +
	"\x12Thread_ReplyThread\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12M\n" +
	"\x12Thread_DeleteReply\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12N\n" +
	"\x1bThread_GetBookmarkedThreads\x12\x14.thread.StringThread\x1a\x19.thread.ApiResponseThread\x12L\n" +
	"\x19Thread_GetRepostedThreads\x12\x14.thread.StringThread\x1a\x19.thread.ApiResponseThread\x12P\n" +
	"\x15Thread_GetUserThreads\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12U\n" +
	"\x1aThread_GetUserLikedThreads\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12P\n" +
	"\x15Thread_GetUserReplies\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThread\x12U\n" +
	"\x1aThread_GetUserMediaThreads\x12\x1c.thread.GeneralThreadRequest\x1a\x19.thread.ApiResponseThreadB\tZ\athread/b\x06proto3"

var (
	file_thread_proto_rawDescOnce sync.Once
	file_thread_proto_rawDescData []byte
)

func file_thread_proto_rawDescGZIP() []byte {
	file_thread_proto_rawDescOnce.Do(func() {
		file_thread_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thread_proto_rawDesc), len(file_thread_proto_rawDesc)))
	})
	return file_thread_proto_rawDescData
}

var file_thread_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_thread_proto_goTypes = []any{
	(*ApiResponseThread)(nil),            // 0: thread.ApiResponseThread
	(*SearchThreadRequest)(nil),          // 1: thread.SearchThreadRequest
	(*StringThread)(nil),                 // 2: thread.StringThread
	(*SubmitVote)(nil),                   // 3: thread.SubmitVote
	(*ReplyThread)(nil),                  // 4: thread.ReplyThread
	(*GeneralThreadRequest)(nil),         // 5: thread.GeneralThreadRequest
	(*Thread)(nil),                       // 6: thread.Thread
	(*Media)(nil),                        // 7: thread.Media
	(*PollOption)(nil),                   // 8: thread.PollOption
	(*ThreadLike)(nil),                   // 9: thread.ThreadLike
	(*ThreadRepost)(nil),                 // 10: thread.ThreadRepost
	(*ThreadReply)(nil),                  // 11: thread.ThreadReply
	(*GetAllThreadsRequest)(nil),         // 12: thread.GetAllThreadsRequest
	(*GetThreadsByUserRequest)(nil),      // 13: thread.GetThreadsByUserRequest
	(*GetThreadsByCommunityRequest)(nil), // 14: thread.GetThreadsByCommunityRequest
	(*PostThread)(nil),                   // 15: thread.PostThread
	(*GetThreadsResponse)(nil),           // 16: thread.GetThreadsResponse
	(*DeleteThreadRequest)(nil),          // 17: thread.DeleteThreadRequest
	(*RepostRequest)(nil),                // 18: thread.RepostRequest
	(*anypb.Any)(nil),                    // 19: google.protobuf.Any
}
var file_thread_proto_depIdxs = []int32{
	19, // 0: thread.ApiResponseThread.data:type_name -> google.protobuf.Any
	7,  // 1: thread.Thread.media:type_name -> thread.Media
	8,  // 2: thread.Thread.poll_options:type_name -> thread.PollOption
	6,  // 3: thread.GetThreadsResponse.threads:type_name -> thread.Thread
	12, // 4: thread.ThreadService.Thread_GetAllThreads:input_type -> thread.GetAllThreadsRequest
	12, // 5: thread.ThreadService.Thread_SearchThreads:input_type -> thread.GetAllThreadsRequest
	17, // 6: thread.ThreadService.Thread_DeleteThread:input_type -> thread.DeleteThreadRequest
	15, // 7: thread.ThreadService.Thread_CreateThread:input_type -> thread.PostThread
	5,  // 8: thread.ThreadService.Thread_PinThread:input_type -> thread.GeneralThreadRequest
	5,  // 9: thread.ThreadService.Thread_UnPinThread:input_type -> thread.GeneralThreadRequest
	3,  // 10: thread.ThreadService.Thread_VoteThread:input_type -> thread.SubmitVote
	5,  // 11: thread.ThreadService.Thread_ToggleLike:input_type -> thread.GeneralThreadRequest
	5,  // 12: thread.ThreadService.Thread_ToggleBookmark:input_type -> thread.GeneralThreadRequest
	18, // 13: thread.ThreadService.Thread_ToggleRepost:input_type -> thread.RepostRequest
	5,  // 14: thread.ThreadService.Thread_ReplyThread:input_type -> thread.GeneralThreadRequest
	5,  // 15: thread.ThreadService.Thread_DeleteReply:input_type -> thread.GeneralThreadRequest
	2,  // 16: thread.ThreadService.Thread_GetBookmarkedThreads:input_type -> thread.StringThread
	2,  // 17: thread.ThreadService.Thread_GetRepostedThreads:input_type -> thread.StringThread
	5,  // 18: thread.ThreadService.Thread_GetUserThreads:input_type -> thread.GeneralThreadRequest
	5,  // 19: thread.ThreadService.Thread_GetUserLikedThreads:input_type -> thread.GeneralThreadRequest
	5,  // 20: thread.ThreadService.Thread_GetUserReplies:input_type -> thread.GeneralThreadRequest
	5,  // 21: thread.ThreadService.Thread_GetUserMediaThreads:input_type -> thread.GeneralThreadRequest
	0,  // 22: thread.ThreadService.Thread_GetAllThreads:output_type -> thread.ApiResponseThread
	0,  // 23: thread.ThreadService.Thread_SearchThreads:output_type -> thread.ApiResponseThread
	0,  // 24: thread.ThreadService.Thread_DeleteThread:output_type -> thread.ApiResponseThread
	0,  // 25: thread.ThreadService.Thread_CreateThread:output_type -> thread.ApiResponseThread
	0,  // 26: thread.ThreadService.Thread_PinThread:output_type -> thread.ApiResponseThread
	0,  // 27: thread.ThreadService.Thread_UnPinThread:output_type -> thread.ApiResponseThread
	0,  // 28: thread.ThreadService.Thread_VoteThread:output_type -> thread.ApiResponseThread
	0,  // 29: thread.ThreadService.Thread_ToggleLike:output_type -> thread.ApiResponseThread
	0,  // 30: thread.ThreadService.Thread_ToggleBookmark:output_type -> thread.ApiResponseThread
	0,  // 31: thread.ThreadService.Thread_ToggleRepost:output_type -> thread.ApiResponseThread
	0,  // 32: thread.ThreadService.Thread_ReplyThread:output_type -> thread.ApiResponseThread
	0,  // 33: thread.ThreadService.Thread_DeleteReply:output_type -> thread.ApiResponseThread
	0,  // 34: thread.ThreadService.Thread_GetBookmarkedThreads:output_type -> thread.ApiResponseThread
	0,  // 35: thread.ThreadService.Thread_GetRepostedThreads:output_type -> thread.ApiResponseThread
	0,  // 36: thread.ThreadService.Thread_GetUserThreads:output_type -> thread.ApiResponseThread
	0,  // 37: thread.ThreadService.Thread_GetUserLikedThreads:output_type -> thread.ApiResponseThread
	0,  // 38: thread.ThreadService.Thread_GetUserReplies:output_type -> thread.ApiResponseThread
	0,  // 39: thread.ThreadService.Thread_GetUserMediaThreads:output_type -> thread.ApiResponseThread
	22, // [22:40] is the sub-list for method output_type
	4,  // [4:22] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_thread_proto_init() }
func file_thread_proto_init() {
	if File_thread_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thread_proto_rawDesc), len(file_thread_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thread_proto_goTypes,
		DependencyIndexes: file_thread_proto_depIdxs,
		MessageInfos:      file_thread_proto_msgTypes,
	}.Build()
	File_thread_proto = out.File
	file_thread_proto_goTypes = nil
	file_thread_proto_depIdxs = nil
}
